# Initial processing and imports

In [1]:
import pandas as pd, geopandas as gpd
from rapidfuzz import process, fuzz
from tqdm import tqdm
from shapely import Point

In [7]:
def parse_gps(lat_str, lon_str):
    """Parse GPS coordinates from Polish DMS format like "21*22'806" to decimal degrees"""
    if pd.isna(lat_str) or lat_str == '' or pd.isna(lon_str) or lon_str == '':
        return None
    try:
        # Try direct float conversion first (for decimal degrees)
        return float(lat_str), float(lon_str)
    except:
        try:
            # Parse degree*minute'second format like "21*22'806"
            if '*' in str(lat_str) and "'" in str(lat_str) and '*' in str(lon_str) and "'" in str(lon_str):
                lat_str, lon_str = str(lat_str).replace(',','').replace("''","'"), str(lon_str).replace(',','').replace("''","'")
                parts_lat, parts_lon = lat_str.split('*'), lon_str.split('*')
                min_sec_lat, min_sec_lon = parts_lat[1].split("'"), parts_lon[1].split("'")
                minutes_lat, minutes_lon = float(min_sec_lat[0]), float(min_sec_lon[0])
                seconds_lat, seconds_lon = float(min_sec_lat[0]), float(min_sec_lon[0])

                if minutes_lat > 59 or minutes_lon > 59 or seconds_lat >= 600 or seconds_lon >= 600:
                    return parse_as_decimal(lat_str), parse_as_decimal(lon_str)
                else:
                    return parse_as_degrees(lat_str), parse_as_degrees(lon_str)
            else:
                print(f"Error parsing coordinate '{lat_str} {lon_str}': Invalid format")  # Fixed undefined 'e'
                return None
        except Exception as e:
            print(f"Error parsing coordinate '{lat_str} {lon_str}': {e}")
            return None

def parse_as_decimal(coord_str):
    try:
        return float(coord_str)
    except:
        parts = coord_str.split('*', maxsplit=1)
        ms = parts[1].split("'", maxsplit=1)

        try:
            parts[0] = parts[0].replace("*", "0")
            ms[0] = ms[0].strip("*,`''").replace("''", "'").replace("*", "0")
            ms[1] = ms[1].strip("*,`''").replace("''", "'").replace("*", "0")
            ms[1] = 0 if ms[1] == '' else ms[1]
            if len(ms[1]) <= 2:
                div = 1
            else:
                div = 10
            return float(parts[0]) + float(ms[0])/100 + (float(ms[1])/div)/10000
        except Exception as e:
            print(f"Error parsing coordinate '{coord_str}': {e}")
            return None

def parse_as_degrees(coord_str):
    try:
        return float(coord_str)
    except:
        parts = coord_str.split('*', maxsplit=1)
        ms = parts[1].split("'", maxsplit=1)
        
        try:
            parts[0] = parts[0].replace("*", "0")
            ms[0] = ms[0].strip("*,`''").replace("''", "'").replace("*", "0")
            ms[1] = ms[1].strip("*,`''").replace("''", "'").replace("*", "0")
            ms[1] = 0 if ms[1] == '' else ms[1]

            if len(ms[1]) <= 2:
                div = 1
            elif len(ms[1]) == 3:
                div = 10
            elif len(ms[1]) == 4:
                div = 100
            else:
                div = 10

            return float(parts[0]) + float(ms[0])/60 + (float(ms[1])/div)/3600
        except Exception as e:
            print(f"Error parsing coordinate '{coord_str}': {e}")
            return None

def best_match(street, choices):
    """Return best fuzzy match + score from a list of choices"""
    if pd.isna(street) or not choices:
        return None, 0
    match, score, _ = process.extractOne(
        street, choices, scorer=fuzz.token_sort_ratio
    )
    return match, score

In [5]:
gminy = gpd.read_file("gis/A03_Granice_gmin.shp", encoding='utf-8').to_crs(4326)
powiaty = gpd.read_file("gis/A02_Granice_powiatow.shp", encoding='utf-8').to_crs(4326)
wojewodztwa = gpd.read_file("gis/A01_Granice_wojewodztw.shp", encoding='utf-8').to_crs(4326)

In [3]:
if False:
    osm_streets = gpd.read_file("poland_pbf/poland-250914.osm.pbf", layer="lines")

    osm_types = [
        'residential', 'tertiary', 'pedestrian', 'secondary',
        'living_street', 'primary', 'unclassified', 'service',
        'secondary_link', 'trunk', 'construction', 'primary_link',
        'motorway', 'tertiary_link', 'trunk_link', 'motorway_link']
    osm_streets = osm_streets[osm_streets["highway"].isin(osm_types)]

    osm_streets = osm_selected_streets[["name", "highway", "geometry"]].copy()
    osm_streets = osm_streets.sjoin(gminy[["JPT_NAZWA_", "JPT_KOD_JE", "geometry"]], how="left")
    osm_streets.drop(['index_right'], axis=1, errors="ignore").to_file('gis/roads_poland.shp')
else:
    osm_streets = gpd.read_file('gis/roads_poland.shp')

In [4]:
def extract_osm_attribute(df: pd.DataFrame, source_attr_name, target_attr_name):
    df[f"{source_attr_name}_loc"] = df["other_tags"].str.find(f'{source_attr_name}') + len(f'"{source_attr_name}"=>"')
    df[f"{source_attr_name}_loc_end"] = df.apply(lambda x: x["other_tags"].find('"', x[f'{source_attr_name}_loc']), axis=1)
    df[f"{target_attr_name}"] = df.apply(lambda x: x["other_tags"][x[f"{source_attr_name}_loc"]-1:x[f"{source_attr_name}_loc_end"]], axis=1)
    return df

if False:
    # EXTRACT ADDRESSES FROM POLYGONS (BUILDINGS)
    osm_points = gpd.read_file("poland_pbf/poland-250914.osm.pbf", layer="points")
    osm_polygons = gpd.read_file("poland_pbf/poland-250914.osm.pbf", layer="multipolygons")

    addresses_b = osm_polygons.loc[(~osm_polygons["other_tags"].isna()) & (osm_polygons["other_tags"].str.contains("addr")), ["geometry", "other_tags"]]

    addresses_b["geometry"] = addresses_b.to_crs('+proj=cea').centroid.to_crs(addresses_b.crs)
    addresses_b = extract_osm_attribute(addresses_b, 'addr:housenumber', 'addr_num')
    addresses_b = extract_osm_attribute(addresses_b, 'addr:street', 'street_nm')
    addresses_b = addresses_b[["addr_num", "street_nm", "geometry"]]
    addresses_b = addresses_b.sjoin(gminy[["JPT_NAZWA_", "JPT_KOD_JE", "geometry"]], how="left")

    # EXTRACT ADDRESSES FROM POINTS

    addresses_p = osm_points.loc[(~osm_points["other_tags"].isna()) & (osm_points["other_tags"].str.contains("addr")), ["geometry", "other_tags"]]

    addresses_p = extract_osm_attribute(addresses_p, 'addr:housenumber', 'addr_num')
    addresses_p = extract_osm_attribute(addresses_p, 'addr:street', 'street_nm')
    addresses_p = addresses_p[["addr_num", "street_nm", "geometry"]]
    addresses_p = addresses_p.sjoin(gminy[["JPT_NAZWA_", "JPT_KOD_JE", "geometry"]], how="left")

    # MERGE AND SAVE
    osm_adresses = pd.concat([addresses_b, addresses_p])
    osm_adresses.drop(['index_right'], axis=1, errors="ignore").to_file('gis/addr_poland.shp')
else:
    osm_adresses = gpd.read_file('gis/addr_poland.shp')

In [8]:
accidents_df = pd.read_csv("csv/sewik_accidents.csv")

# Remove columns that start with "Unnamed:"
accidents_df = accidents_df.loc[:, ~accidents_df.columns.str.contains('^Unnamed')]

parse_gps_coords = True
if parse_gps_coords:
    coords = accidents_df.apply(lambda row: parse_gps(row['WSP_GPS_Y'], row['WSP_GPS_X']), axis=1)
    
    coord_list = coords.tolist()
    accidents_df['lat'] = pd.Series([coord[0] if coord is not None else None for coord in coord_list])
    accidents_df['lon'] = pd.Series([coord[1] if coord is not None else None for coord in coord_list])

    # Convert to numeric, coercing errors to NaN
    accidents_df['lon'] = pd.to_numeric(accidents_df['lon'], errors='coerce')
    accidents_df['lat'] = pd.to_numeric(accidents_df['lat'], errors='coerce')

accidents_df = gpd.GeoDataFrame(
    accidents_df, 
    geometry=gpd.GeoSeries.from_xy(
        accidents_df["lon"], accidents_df["lat"], crs="WGS84")
)
if False:
    # accidents_df.drop("geometry", axis=1).to_csv("csv/sewik_accidents.csv", index=False)

    accidents_df.loc[
        accidents_df.geometry.is_valid,
            [
                'ID', 'year', 'WOJ', 'WSP_GPS_X', 'WSP_GPS_Y', 'MIEJSCOWOSC' ,
                'ULICA_ADRES', 'NUMER_DOMU', "geometry"]
            ].to_file('gis/sewik_accidents_points.shp', driver='ESRI Shapefile')

C:\Users\Witold\AppData\Local\Temp\ipykernel_10756\3255738446.py:1: DtypeWarning: Columns (9,10,49) have mixed types. Specify dtype option on import or set low_memory=False.
  accidents_df = pd.read_csv("csv/sewik_accidents.csv")

Error parsing coordinate '52*11'28/': could not convert string to float: '28/'
Error parsing coordinate '52*25'': object of type 'int' has no len()
Error parsing coordinate '2-*47'855': could not convert string to float: '2-'
Error parsing coordinate '52*18'': object of type 'int' has no len()
Error parsing coordinate '`5*21'526': could not convert string to float: '`5'
Error parsing coordinate '52*47'': object of type 'int' has no len()
Error parsing coordinate '2**15'495 20*68'528': could not convert string to float: ''
Error parsing coordinate '52*08'38/': could not convert string to float: '38/'
Error parsing coordinate '21*00'5'8': could not convert string to float: "5'8"
Error parsing coordinate '5**26'032 21*04'640': could not convert string to float: ''
Error parsing coordinate '21*15'': object of type 'int' has no len()
Error parsing coordinate '52*14'1-1': could not convert string to float: '1-1'
Error parsing coordinate '52*22'005 2**09'448': could not convert string to float: ''
Error parsing coordinate '53*'3'00 20*26'599': could not convert string to float: ''
Error parsing coordinate '52*19'929 2**09'665': could not convert string to float: ''
Error parsing coordinate '52*''237 21*01'482': could not convert string to float: ''
Error parsing coordinate '52*13'126 21*'1'17': could not convert string to float: ''
Error parsing coordinate '51*47'': object of type 'int' has no len()
Error parsing coordinate '52*27'': object of type 'int' has no len()
Error parsing coordinate '20*98'': object of type 'int' has no len()
Error parsing coordinate '52*22'524 21*'4'041': could not convert string to float: ''
Error parsing coordinate '53*70'': object of type 'int' has no len()
Error parsing coordinate '21*08'': object of type 'int' has no len()
Error parsing coordinate '\2*10'241': could not convert string to float: '\\2'
Error parsing coordinate '53*68'': object of type 'int' has no len()
Error parsing coordinate '51*58'': object of type 'int' has no len()
Error parsing coordinate '52*21'': object of type 'int' has no len()
Error parsing coordinate '5**21'517 21*03'120': could not convert string to float: ''
Error parsing coordinate '52*80'': object of type 'int' has no len()
Error parsing coordinate '17*03'': object of type 'int' has no len()
Error parsing coordinate '53*27'467 1846392': Invalid format
Error parsing coordinate '53*28'379 18464082': Invalid format
Error parsing coordinate '5**30'071 18*00'192': could not convert string to float: ''
Error parsing coordinate '52*37'420 18*/5'735': could not convert string to float: '/5'
Error parsing coordinate '53*29'501 18451389': Invalid format
Error parsing coordinate '53*28'051 18*/5'659': could not convert string to float: '/5'
Error parsing coordinate '53*09'': object of type 'int' has no len()
Error parsing coordinate '52*47'': object of type 'int' has no len()
Error parsing coordinate '53*04'4'3': could not convert string to float: "4'3"
Error parsing coordinate '52*79'': object of type 'int' has no len()
Error parsing coordinate '53*30'149 18455244': Invalid format
Error parsing coordinate '`5*34'667': could not convert string to float: '`5'
Error parsing coordinate '52*10'': object of type 'int' has no len()
Error parsing coordinate '20*01'': object of type 'int' has no len()
Error parsing coordinate '51.880110 16.,07678': Invalid format
Error parsing coordinate '15*43'': object of type 'int' has no len()
Error parsing coordinate '4**55'099 19*52'497': could not convert string to float: ''
Error parsing coordinate '50*24'111 200815059': Invalid format
Error parsing coordinate '49*'2'902 20*04'512': could not convert string to float: ''
Error parsing coordinate '/2*00'530': could not convert string to float: '/2'
Error parsing coordinate '49*26'/25': could not convert string to float: '/25'
Error parsing coordinate '40.968773 20*24'323': Invalid format
Error parsing coordinate '4**93'718 20*41'350': could not convert string to float: ''
Error parsing coordinate '50*21'542 1**95'115': could not convert string to float: ''
Error parsing coordinate '4**52'410 19*47'432': could not convert string to float: ''
Error parsing coordinate '1/*15'277': could not convert string to float: '1/'
Error parsing coordinate '1/*25'000': could not convert string to float: '1/'
Error parsing coordinate '17*54'08/': could not convert string to float: '08/'
Error parsing coordinate '51*''050 17*45'200': could not convert string to float: ''
Error parsing coordinate '50*46'377 17**3'4'5': could not convert string to float: ''
Error parsing coordinate '49*57'030 22.4854,': Invalid format
Error parsing coordinate '50*1'192 22.3855,': Invalid format
Error parsing coordinate '9**52'599 21*54'314': could not convert string to float: ''
Error parsing coordinate '50*1'144 22.3959,': Invalid format
Error parsing coordinate '49.9973, 22.6799,': Invalid format
Error parsing coordinate '49.5650. 22*33'179': Invalid format
Error parsing coordinate '49*57'180 23.643,': Invalid format
Error parsing coordinate '50.00218. 22.72914.': Invalid format
Error parsing coordinate '56.021452 22*38'214': Invalid format
Error parsing coordinate '50*01'171 22.6990,': Invalid format
Error parsing coordinate '59.56721 22*03'348': Invalid format
Error parsing coordinate '50*04'223 21': Invalid format
Error parsing coordinate '49*42'': object of type 'int' has no len()
Error parsing coordinate '21*44'': object of type 'int' has no len()
Error parsing coordinate '18*20'149 5.476828': Invalid format
Error parsing coordinate 'E1*90'623': could not convert string to float: 'E1'
Error parsing coordinate '4**56'569 18*35'410': could not convert string to float: ''
Error parsing coordinate '52.30,061 17*00'510': Invalid format
Error parsing coordinate '51*48'/53': could not convert string to float: '/53'
Error parsing coordinate '17*3'': object of type 'int' has no len()
Error parsing coordinate '52.20692P 18*13'574': Invalid format
Error parsing coordinate '52*44'': object of type 'int' has no len()
Error parsing coordinate '52 18*19'020': Invalid format
Error parsing coordinate '52*38'': object of type 'int' has no len()
Error parsing coordinate '16*29'': object of type 'int' has no len()
Error parsing coordinate '53*'1'128 14*26'206': could not convert string to float: ''
Error parsing coordinate '53*74'': object of type 'int' has no len()
Error parsing coordinate '52*52'45N': could not convert string to float: '45N'
Error parsing coordinate '14*12'08E': could not convert string to float: '08E'
Error parsing coordinate '35**3'5*3 15**1'5*1': could not convert string to float: ''
Error parsing coordinate '54**5'4*5 15**1'5*2': could not convert string to float: ''
Error parsing coordinate '49*45'445 15**1'5*1': could not convert string to float: ''
Error parsing coordinate '50*64'/89': could not convert string to float: '/89'
Error parsing coordinate '20*37'': object of type 'int' has no len()
Error parsing coordinate '51*08'': object of type 'int' has no len()
Error parsing coordinate '16*52'': object of type 'int' has no len()
Error parsing coordinate '16*55'3'2': could not convert string to float: "3'2"
Error parsing coordinate '51*10'': object of type 'int' has no len()
Error parsing coordinate '17*04'': object of type 'int' has no len()
Error parsing coordinate '50*45'5/3': could not convert string to float: '5/3'
Error parsing coordinate '51*13'': object of type 'int' has no len()
Error parsing coordinate '17*07'': object of type 'int' has no len()
Error parsing coordinate '17*01'4'0': could not convert string to float: "4'0"
Error parsing coordinate '52*46'396 18*/1'417': could not convert string to float: '/1'
Error parsing coordinate '2**38'499 19*04'009': could not convert string to float: ''
Error parsing coordinate '19*04'52-': could not convert string to float: '52-'
Error parsing coordinate '19*00'5'6': could not convert string to float: "5'6"
Error parsing coordinate '53*47'': object of type 'int' has no len()
Error parsing coordinate '18*15'': object of type 'int' has no len()
Error parsing coordinate '52*40'': object of type 'int' has no len()
Error parsing coordinate '19*17'': object of type 'int' has no len()
Error parsing coordinate '5**20'134 19*59'597': could not convert string to float: ''
Error parsing coordinate '50*33'462 23*0-'801': could not convert string to float: '0-'
Error parsing coordinate 'E2*33'742': could not convert string to float: 'E2'
Error parsing coordinate '51*4/'312 16*18'228': could not convert string to float: '4/'
Error parsing coordinate '55.156390 15*29'279': Invalid format
Error parsing coordinate '52*20'26 21*'2'45': could not convert string to float: ''
Error parsing coordinate '21*07'': object of type 'int' has no len()
Error parsing coordinate '21*28'': object of type 'int' has no len()
Error parsing coordinate 'N5*20'736': could not convert string to float: 'N5'
Error parsing coordinate '21*09'': object of type 'int' has no len()
Error parsing coordinate '52*86'': object of type 'int' has no len()
Error parsing coordinate '21*54'': object of type 'int' has no len()
Error parsing coordinate '21*03'': object of type 'int' has no len()
Error parsing coordinate '20*56'58/': could not convert string to float: '58/'
Error parsing coordinate '52*16'3 21*1"'57': could not convert string to float: '1"'
Error parsing coordinate '21*12'': object of type 'int' has no len()
Error parsing coordinate '51*47'': object of type 'int' has no len()
Error parsing coordinate '52*18'': object of type 'int' has no len()
Error parsing coordinate '21*13'': object of type 'int' has no len()
Error parsing coordinate '21*10'6'9': could not convert string to float: "6'9"
Error parsing coordinate '21*55'3/3': could not convert string to float: '3/3'
Error parsing coordinate '52 21*32'412': Invalid format
Error parsing coordinate '21*00'': object of type 'int' has no len()
Error parsing coordinate '52*15'': object of type 'int' has no len()
Error parsing coordinate '5**36'009 21*27'162': could not convert string to float: ''
Error parsing coordinate '21*09'': object of type 'int' has no len()
Error parsing coordinate '52*62'': object of type 'int' has no len()
Error parsing coordinate '52*26'57 21*'5'81': could not convert string to float: ''
Error parsing coordinate '52*70'': object of type 'int' has no len()
Error parsing coordinate '21*13'': object of type 'int' has no len()
Error parsing coordinate '21*16'': object of type 'int' has no len()
Error parsing coordinate '20*58'3'3': could not convert string to float: "3'3"
Error parsing coordinate '20*17'': object of type 'int' has no len()
Error parsing coordinate '21*16'': object of type 'int' has no len()
Error parsing coordinate '52*15'': object of type 'int' has no len()
Error parsing coordinate '21*19'': object of type 'int' has no len()
Error parsing coordinate '21*04'': object of type 'int' has no len()
Error parsing coordinate '2**01'494 20*40'094': could not convert string to float: ''
Error parsing coordinate '21*99'': object of type 'int' has no len()
Error parsing coordinate '21*06'': object of type 'int' has no len()
Error parsing coordinate '21*06'': object of type 'int' has no len()
Error parsing coordinate '21*14'': object of type 'int' has no len()
Error parsing coordinate '21*12'': object of type 'int' has no len()
Error parsing coordinate '21*29'': object of type 'int' has no len()
Error parsing coordinate '21*09'41A': could not convert string to float: '41A'
Error parsing coordinate '52*47'': object of type 'int' has no len()
Error parsing coordinate '21*20'': object of type 'int' has no len()
Error parsing coordinate '21*42'': object of type 'int' has no len()
Error parsing coordinate '21*37'': object of type 'int' has no len()
Error parsing coordinate '49.,69797 20*25'517': Invalid format
Error parsing coordinate '6*2+'3+5 19*33'599': could not convert string to float: '2+'
Error parsing coordinate '20*42'58Z': could not convert string to float: '58Z'
Error parsing coordinate '4**52'386 20*06'102': could not convert string to float: ''
Error parsing coordinate '4**53'313 19*49'425': could not convert string to float: ''
Error parsing coordinate 'WW*30'420': could not convert string to float: 'WW'
Error parsing coordinate '5-*-5'940': could not convert string to float: '5-'
Error parsing coordinate '499103358 21*49'500': Invalid format
Error parsing coordinate '50*14'462 21*`4'651': could not convert string to float: '`4'
Error parsing coordinate '22*08'/47': could not convert string to float: '/47'
Error parsing coordinate '22*05'1'2': could not convert string to float: "1'2"
Error parsing coordinate 'E2*33'446': could not convert string to float: 'E2'
Error parsing coordinate '17*03'0'1': could not convert string to float: "0'1"
Error parsing coordinate '18*38'/51': could not convert string to float: '/51'
Error parsing coordinate '51*44'339 18*'0'27': could not convert string to float: ''
Error parsing coordinate '52*28'': object of type 'int' has no len()
Error parsing coordinate '51*25'': object of type 'int' has no len()
Error parsing coordinate '17*56'': object of type 'int' has no len()
Error parsing coordinate '52.398/68 17*09'348': Invalid format
Error parsing coordinate '52*40'': object of type 'int' has no len()
Error parsing coordinate '16*93'': object of type 'int' has no len()
Error parsing coordinate '51*44'362 18*O5'466': could not convert string to float: 'O5'
Error parsing coordinate '52.38823V 16*45'476': Invalid format
Error parsing coordinate '53*25'': object of type 'int' has no len()
Error parsing coordinate '14*31'': object of type 'int' has no len()
Error parsing coordinate '53ZX 14*58'302': Invalid format
Error parsing coordinate '53*25'': object of type 'int' has no len()
Error parsing coordinate '14*32'': object of type 'int' has no len()
Error parsing coordinate '54*5;'408 15*15'595': could not convert string to float: '5;'
Error parsing coordinate '53*25'': object of type 'int' has no len()
Error parsing coordinate '14*32'': object of type 'int' has no len()
Error parsing coordinate '53*25'': object of type 'int' has no len()
Error parsing coordinate '14*32'': object of type 'int' has no len()
Error parsing coordinate '16*28'': object of type 'int' has no len()
Error parsing coordinate '51.04808/ 20*49'546': Invalid format
Error parsing coordinate '`5*02'235': could not convert string to float: '`5'
Error parsing coordinate '49.55 219 19.32 206': Invalid format
Error parsing coordinate '19*57'': object of type 'int' has no len()
Error parsing coordinate '49*49'39-': could not convert string to float: '39-'
Error parsing coordinate '20*14'': object of type 'int' has no len()
Error parsing coordinate '51*37'4'3': could not convert string to float: "4'3"
Error parsing coordinate '51*25'': object of type 'int' has no len()
Error parsing coordinate '16*22'': object of type 'int' has no len()
Error parsing coordinate '52*52'': object of type 'int' has no len()
Error parsing coordinate '53.506283 18.,63845': Invalid format
Error parsing coordinate '19*08'0'1': could not convert string to float: "0'1"
Error parsing coordinate '18*00'': object of type 'int' has no len()
Error parsing coordinate '4/*12'230': could not convert string to float: '4/'
Error parsing coordinate '53*''065 19*40'873': could not convert string to float: ''
Error parsing coordinate '21*14'': object of type 'int' has no len()
Error parsing coordinate '21*38'': object of type 'int' has no len()
Error parsing coordinate '21*29'': object of type 'int' has no len()
Error parsing coordinate '21*06'06W': could not convert string to float: '06W'
Error parsing coordinate '21*21'': object of type 'int' has no len()
Error parsing coordinate '21*18'': object of type 'int' has no len()
Error parsing coordinate '52*11'1'6': could not convert string to float: "1'6"
Error parsing coordinate '5**20'830 21*02'10': could not convert string to float: ''
Error parsing coordinate '52*14'3'1': could not convert string to float: "3'1"
Error parsing coordinate '20*99'': object of type 'int' has no len()
Error parsing coordinate '21*14'': object of type 'int' has no len()
Error parsing coordinate '21*40'': object of type 'int' has no len()
Error parsing coordinate '5**24'253 22*14'05': could not convert string to float: ''
Error parsing coordinate '52*1-'359 20*53'450': could not convert string to float: '1-'
Error parsing coordinate '21*17'': object of type 'int' has no len()
Error parsing coordinate '52*19'H': could not convert string to float: 'H'
Error parsing coordinate '52*16'': object of type 'int' has no len()
Error parsing coordinate '52,462063 20*34'289': Invalid format
Error parsing coordinate '21*09'': object of type 'int' has no len()
Error parsing coordinate '21*20'': object of type 'int' has no len()
Error parsing coordinate '2-*52'220': could not convert string to float: '2-'
Error parsing coordinate '52*37'': object of type 'int' has no len()
Error parsing coordinate '21*21'': object of type 'int' has no len()
Error parsing coordinate '17*45'5'9': could not convert string to float: "5'9"
Error parsing coordinate '50*46'239 17341169': Invalid format
Error parsing coordinate '51*02'': object of type 'int' has no len()
Error parsing coordinate '1\*17'125': could not convert string to float: '1\\'
Error parsing coordinate '50*03'': object of type 'int' has no len()
Error parsing coordinate '21.,77250 49.,68096': Invalid format
Error parsing coordinate '49*27'574 22475157': Invalid format
Error parsing coordinate '21*51'5'7': could not convert string to float: "5'7"
Error parsing coordinate '5-*1-'816 22*49'926': could not convert string to float: '1-'
Error parsing coordinate 'N4*92'558': could not convert string to float: 'N4'
Error parsing coordinate '50022862 22*02'168': Invalid format
Error parsing coordinate '53*09'26H': could not convert string to float: '26H'
Error parsing coordinate '52.6443,8 16*49'114': Invalid format
Error parsing coordinate '52*18'956 17*''320': could not convert string to float: ''
Error parsing coordinate '51*46'021 18*O5'453': could not convert string to float: 'O5'
Error parsing coordinate '17*09'0'1': could not convert string to float: "0'1"
Error parsing coordinate '51*31'': object of type 'int' has no len()
Error parsing coordinate '18*02'': object of type 'int' has no len()
Error parsing coordinate '50*43'280 20*3\'634': could not convert string to float: '3\\'
Error parsing coordinate '500531211 20*393962': Invalid format
Error parsing coordinate '50*533358 20*391764': Invalid format
Error parsing coordinate '50*52420 20*36'444': Invalid format
Error parsing coordinate '50*541247 20*401879': Invalid format
Error parsing coordinate '20*37'': object of type 'int' has no len()
Error parsing coordinate 'Q5*03'630': could not convert string to float: 'Q5'
Error parsing coordinate '5-*15'122': could not convert string to float: '5-'
Error parsing coordinate '\2*03'817': could not convert string to float: '\\2'
Error parsing coordinate '51*30'': object of type 'int' has no len()
Error parsing coordinate '52*38'37 19*'5'48': could not convert string to float: ''
Error parsing coordinate '53012314 18*36'547': Invalid format
Error parsing coordinate '53*33'': object of type 'int' has no len()
Error parsing coordinate '18*70'': object of type 'int' has no len()
Error parsing coordinate '21*61'': object of type 'int' has no len()
Error parsing coordinate '21*51'': object of type 'int' has no len()
Error parsing coordinate '52,421018 20*44'197': Invalid format
Error parsing coordinate '21*24'': object of type 'int' has no len()
Error parsing coordinate '53*40'': object of type 'int' has no len()
Error parsing coordinate '1**17'800 21*03'169': could not convert string to float: ''
Error parsing coordinate '5**21'316 20*59'14': could not convert string to float: ''
Error parsing coordinate '21*04'': object of type 'int' has no len()
Error parsing coordinate '21*29'': object of type 'int' has no len()

# Preparing spatial data

In [23]:
gminy["JPT_NAZWA_"] = gminy["JPT_NAZWA_"].astype(str).str.upper()
powiaty["JPT_NAZWA_"] = powiaty["JPT_NAZWA_"].astype(str).str.upper()
wojewodztwa["JPT_NAZWA_"] = wojewodztwa["JPT_NAZWA_"].astype(str).str.upper()

# Debug: Print initial counts
print(f"Initial gminy count: {len(gminy)}")
print(f"Initial powiaty count: {len(powiaty)}")
print(f"Initial wojewodztwa count: {len(wojewodztwa)}")

gminy["JPT_KOD_JE"] = gminy["JPT_KOD_JE"].astype(str)
gminy["KOD_POW"] = gminy["JPT_KOD_JE"].astype(str).str[:4]
gminy["KOD_WOJ"] = gminy["JPT_KOD_JE"].astype(str).str[:2]
powiaty["KOD_WOJ"] = powiaty["JPT_KOD_JE"].astype(str).str[:2]
powiaty["KOD_POW"] = powiaty["JPT_KOD_JE"].astype(str)

powiaty["JPT_KOD_JE"] = powiaty["JPT_KOD_JE"]
wojewodztwa["JPT_KOD_JE"] = wojewodztwa["JPT_KOD_JE"]

# Debug: Check for missing KOD_POW matches before merge
gminy_kod_pow = set(gminy["KOD_POW"].unique())
powiaty_kod_pow = set(powiaty["KOD_POW"].unique())
missing_pow_codes = gminy_kod_pow - powiaty_kod_pow
print(f"Unique KOD_POW in gminy: {len(gminy_kod_pow)}")
print(f"Unique KOD_POW in powiaty: {len(powiaty_kod_pow)}")
print(f"Missing KOD_POW codes in powiaty: {len(missing_pow_codes)}")
if missing_pow_codes:
    print(f"Missing codes sample: {list(missing_pow_codes)[:10]}")

# Use outer join to preserve all gminas and identify missing matches
gminy_powiaty = gminy[["JPT_KOD_JE", "JPT_NAZWA_", "KOD_POW"]].rename({"JPT_KOD_JE": "KOD_GMI", "JPT_NAZWA_": "GMINA"}, axis=1).merge(
    powiaty[["JPT_KOD_JE", "JPT_NAZWA_", "KOD_WOJ"]].rename({"JPT_NAZWA_": "POWIAT", "JPT_KOD_JE": "KOD_POW"}, axis=1),
    on="KOD_POW", how="left")

Initial gminy count: 2479
Initial powiaty count: 380
Initial wojewodztwa count: 16
Unique KOD_POW in gminy: 380
Unique KOD_POW in powiaty: 380
Missing KOD_POW codes in powiaty: 0

In [24]:


print(f"After first merge: {len(gminy_powiaty)}")
print(f"Records with missing POWIAT: {len(gminy_powiaty[gminy_powiaty['POWIAT'].isna()])}")

# Check for missing KOD_WOJ matches before second merge
gminy_kod_woj = set(gminy_powiaty["KOD_WOJ"].dropna().unique())
wojewodztwa_kod_woj = set(wojewodztwa["JPT_KOD_JE"].unique())
missing_woj_codes = gminy_kod_woj - wojewodztwa_kod_woj
print(f"Missing KOD_WOJ codes in wojewodztwa: {len(missing_woj_codes)}")

gminy_powiaty = gminy_powiaty.merge(
    wojewodztwa[["JPT_KOD_JE", "JPT_NAZWA_"]].rename({"JPT_NAZWA_": "WOJ", "JPT_KOD_JE": "KOD_WOJ"}, axis=1),
    on="KOD_WOJ", how="left")

print(f"After second merge: {len(gminy_powiaty)}")
print(f"Records with missing WOJ: {len(gminy_powiaty[gminy_powiaty['WOJ'].isna()])}")

# Show samples of missing data for debugging
if len(gminy_powiaty[gminy_powiaty["POWIAT"].isna()]) > 0:
    print("\nSample gminas without matching powiat:")
    print(gminy_powiaty[gminy_powiaty["POWIAT"].isna()][["GMINA", "KOD_POW"]].head())

# Modified condition to warn instead of raise exception
missing_powiaty = gminy_powiaty[gminy_powiaty["POWIAT"].isna()]
if len(missing_powiaty) > 0:
    print(f"WARNING: {len(missing_powiaty)} gminas could not be matched to powiaty")
    # You can choose to either filter them out or keep them with missing data
    # gminy_powiaty = gminy_powiaty.dropna(subset=["POWIAT"])  # Uncomment to remove unmatched records

powiaty_for_join = gminy_powiaty[~gminy_powiaty[["KOD_POW"]].duplicated(keep='first')][["KOD_POW", "POWIAT", "KOD_WOJ", "WOJ"]]
print(f"Final powiaty_for_join count: {len(powiaty_for_join)}")

gminy_obwarzanki = gminy_powiaty[gminy_powiaty[["WOJ", "POWIAT", "GMINA"]].duplicated(keep=False)]
gminy_obwarzanki.loc[gminy_obwarzanki["KOD_GMI"].str[-1]== '2', "GMINA"] = gminy_obwarzanki.loc[gminy_obwarzanki["KOD_GMI"].str[-1]== '2', "GMINA"] + " - OBSZAR WIEJSKI"
gminy_obwarzanki.loc[gminy_obwarzanki["KOD_GMI"].str[-1]== '1', "GMINA"] = gminy_obwarzanki.loc[gminy_obwarzanki["KOD_GMI"].str[-1]== '1', "GMINA"] + " - OBSZAR MIEJSKI"

gminy_powiaty = pd.concat([gminy_powiaty[~gminy_powiaty[["WOJ", "POWIAT", "GMINA"]].duplicated(keep=False)], gminy_obwarzanki])

gminy_powiaty["GMINA_"] = "POWIAT " + gminy_powiaty["GMINA"]
miasta_na_prawach_powiatu = gminy_powiaty[gminy_powiaty["POWIAT"]==gminy_powiaty["GMINA_"]]
print(f"Miasta na prawach powiatu: {len(miasta_na_prawach_powiatu)}")

print(f"Liczba gmin: {len(gminy_powiaty)}")

After first merge: 2479
Records with missing POWIAT: 0
Missing KOD_WOJ codes in wojewodztwa: 0
After second merge: 2479
Records with missing WOJ: 0
Final powiaty_for_join count: 380
Miasta na prawach powiatu: 66
Liczba gmin: 2479

In [25]:
# czyszczenie gmin
accident_gmina_correspondence = {
    'WARSZAWA BIAŁOŁĘKA': 'WARSZAWA',
    'WARSZAWA MOKOTÓW': 'WARSZAWA',
    'OSTROWICE': 'DRAWSKO POMORSKIE', # zlikwidowana w 2018 z powodu niewyplacalnosci
    'SITKÓWKA-NOWINY': 'NOWINY', # zmiana nazwy
    'JEDLNIA - LETNISKO': 'JEDLNIA-LETNISKO'
}


if "GMINA_org" not in accidents_df.columns:
    for old, new in accident_gmina_correspondence.items():
        accidents_df["GMINA_org"] = accidents_df["GMINA"].str.replace(old, new)
else:
    print ("Column GMINA_org already existing")
    for old, new in accident_gmina_correspondence.items():
        accidents_df["GMINA_org"] = accidents_df["GMINA_org"].str.replace(old, new)

# gminas_to_correct = accidents_df[["GMINA_org", "GMINA"]].drop_duplicates()
# gminas_to_correct = gminas_to_correct[~gminas_to_correct["GMINA"].duplicated(keep=False)]

accidents_df.loc[~accidents_df["GMINA_org"].isin(gminy_obwarzanki["GMINA"]), "GMINA"] = (
    accidents_df.loc[~accidents_df["GMINA_org"].isin(gminy_obwarzanki["GMINA"]), "GMINA_org"]
    .astype(str)
    .str.replace(" - OBSZAR WIEJSKI", "", regex=False)
    .str.replace(" - OBSZAR MIEJSKI", "", regex=False)
)

# accidents_df[(accidents_df["GMINA"].str.contains("KARPACZ")) & (~accidents_df["GMINA_org"].isin(gminy_obwarzanki["GMINA"]))]["GMINA"]

Column GMINA_org already existing

In [26]:
# accidents_df[(accidents_df["GMINA"].str.contains("KARPACZ")) & (~accidents_df["GMINA_org"].isin(gminy_obwarzanki["GMINA"]))]["GMINA"]
acc_join = accidents_df.merge(gminy_powiaty, on=["WOJ", "POWIAT", "GMINA"], how="left")

acc_join_mnp = acc_join.loc[~acc_join["GMINA"].isin(gminy_powiaty["GMINA"])].drop(['KOD_POW', 'KOD_WOJ', 'GMINA', 'KOD_GMI'], axis=1).merge(miasta_na_prawach_powiatu, on=["WOJ", "POWIAT"], how="left")
acc_join_mnp["GMINA"] = acc_join_mnp["GMINA"].str.replace('POWIAT ', '')

acc_join_mnp_remaining = acc_join_mnp[~acc_join_mnp["GMINA"].isna()].copy()
acc_join_mnp_remaining["GMINA"] = acc_join_mnp_remaining["MIEJSCOWOSC"]
acc_join_mnp_remaining = acc_join_mnp_remaining.drop(['KOD_POW', 'KOD_WOJ', 'POWIAT', 'KOD_GMI'], axis=1).merge(gminy_powiaty, on=["WOJ", "GMINA"], how="left")

acc_join_mnp = acc_join_mnp[acc_join_mnp["GMINA"].isna()]

acc_join_mnp_remaining = pd.concat([
        acc_join_mnp_remaining[~(acc_join_mnp_remaining["ID"].duplicated(keep=False))],
        acc_join_mnp_remaining[(acc_join_mnp_remaining["ID"].duplicated(keep="last"))]
    ])

new_accidents_df = pd.concat([
        acc_join.loc[acc_join["GMINA"].isin(gminy_powiaty["GMINA"])],
        acc_join_mnp, acc_join_mnp_remaining
    ])

In [27]:
accidents_df_sjoined = new_accidents_df.sjoin(gminy[["JPT_NAZWA_", "JPT_KOD_JE", "geometry"]], how="left")
name_matches = accidents_df_sjoined["JPT_NAZWA_"].str.upper().isin(
    accidents_df_sjoined["MIEJSCOWOSC"].str.upper())
accidents_df_sjoined[~name_matches]

,ID,DataUtworzenia,DataMod,SzkicZdarzenia,JEDNOSTKA_MIEJSCA,JEDNOSTKA_LIKWIDUJACA,JEDNOSTKA_OPERATORA,NR_KW,KOD_GUS,GPS_X_GUS,...,geometry,KOD_GMI,KOD_POW,KOD_WOJ,GMINA_,GMINA__x,GMINA__y,index_right,JPT_NAZWA_,JPT_KOD_JE
1424,106665950,2018-01-09,2018-01-10,N,WA KPP Sierpc,NaN,WA KPP Sierpc,Ldz PSR-WRD-75/18,1427072,"19,8769433081176",...,POINT (19.78625 52.81703),1427072,1427,14,POWIAT ZAWIDZ,NaN,NaN,1791.0,ZAWIDZ,1427072
4184,106692254,2018-01-24,2018-01-29,N,WA KPP Piaseczno (KSP),NaN,WA KPP Piaseczno (KSP),Ldz 75119/1707/2018,1418044,"21,019505753918",...,POINT (21.21369 52.77275),1418043,1418,14,POWIAT PIASECZNO,NaN,NaN,759.0,SZELKÓW,1411102
4222,106692658,2018-01-24,2018-01-25,N,WA KPP Maków Maz.,WA KPP Maków Maz. Wydział Ruchu Drogowego,WA KPP Maków Maz.,KW 304/2018,1411102,"21,1695750451229",...,POINT (21.20333 52.82081),1411102,1411,14,POWIAT SZELKÓW,NaN,NaN,759.0,SZELKÓW,1411102
4805,106704105,2018-01-30,2018-05-08,N,WA KPP Maków Maz.,WA KPP Maków Maz. Wydział Ruchu Drogowego,WA KPP Maków Maz.,KW 383/2018,1411102,"21,1695750451229",...,POINT (21.24992 52.83739),1411102,1411,14,POWIAT SZELKÓW,NaN,NaN,759.0,SZELKÓW,1411102
5172,106703424,2018-01-29,2018-02-01,N,WA KPP Otwock (KSP),NaN,WA KPP Otwock (KSP),KW 1251/18/ID,1417082,"21,3518979143939",...,POINT (21.24345 52.809),1417082,1417,14,POWIAT WIĄZOWNA,NaN,NaN,759.0,SZELKÓW,1411102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2959030,126676140,2024-10-18,2024-10-21,N,KI Komisariat Sędziszów,KI Komisariat Sędziszów,KI Komisariat Sędziszów,Ldz 570/24/K,2602072,"19,9321851633249",...,POINT (19.97192 50.60225),2602072,2602,26,POWIAT SŁUPIA (JĘDRZEJOWSKA),NaN,NaN,954.0,SŁUPIA (JĘDRZEJOWSKA),2602072
2959690,126712610,2024-11-08,2024-11-12,N,KI KPP Jędrzejów,KI KPP Jędrzejów,KI KPP Jędrzejów,Ldz 618/24/K,2602072,"19,9321851633249",...,POINT (20.02328 50.60778),2602072,2602,26,POWIAT SŁUPIA (JĘDRZEJOWSKA),NaN,NaN,954.0,SŁUPIA (JĘDRZEJOWSKA),2602072
2961154,126776394,2024-12-27,2024-12-30,N,KI Komisariat Sędziszów,KI Komisariat Sędziszów,KI Komisariat Sędziszów,Ldz 710/24/K,2602072,"19,9321851633249",...,POINT (19.85769 50.57133),2602072,2602,26,POWIAT SŁUPIA (JĘDRZEJOWSKA),NaN,NaN,954.0,SŁUPIA (JĘDRZEJOWSKA),2602072
71,109858805,2021-01-30,2021-01-30,N,WA KPP Lipsko,WA KPP Lipsko,WA KPP Lipsko,Ldz 296/2021,1409,21.584411,...,POINT (21.77332 51.24237),NaN,NaN,NaN,NaN,NaN,NaN,844.0,CHOTCZA,1409012
193,124347391,2022-12-29,2022-12-30,N,KK KPP Kraków Okolice Wydział Ruchu Drogowego,KK KPP Kraków Okolice Wydział Ruchu Drogowego,KK KPP Kraków Okolice Wydział Ruchu Drogowego,Ldz 213731/22,1206,19.862025,...,POINT (20.06019 50.16153),NaN,NaN,NaN,NaN,NaN,NaN,1830.0,KOCMYRZÓW-LUBORZYCA,1206052

In [28]:
check = new_accidents_df[~new_accidents_df["ID"].isin(accidents_df_sjoined["ID"])]
if (len(check) > 0) or (len(new_accidents_df) != len(accidents_df_sjoined)) or len(new_accidents_df) != len(accidents_df):
    raise Exception("Some accidents were lost")

In [29]:
accidents_df_sjoined["MIEJSCOWOSC"] = accidents_df_sjoined["MIEJSCOWOSC"].astype(str).str.upper()
osm_streets["JPT_NAZWA_"] = osm_streets["JPT_NAZWA_"].astype(str).str.upper()
osm_streets["name"] = osm_streets["name"].astype(str).str.upper()
osm_streets = osm_streets[osm_streets["name"]!='NONE']

# Loop to correct accident locations

In [44]:
# Ensure both dataframes have the JPT_NAZWA_ column in uppercase for matching
accidents_df_sjoined["JPT_NAZWA_"] = accidents_df_sjoined["JPT_NAZWA_"].str.upper()
osm_streets["JPT_NAZWA_"] = osm_streets["JPT_NAZWA_"].str.upper()

# Get unique municipalities from accidents data

accidents_to_correct = accidents_df_sjoined[
    (
        (accidents_df_sjoined["MIEJSCOWOSC"] == "WARSZAWA") #|
        #(accidents_df_sjoined["JPT_KOD_JE"] != accidents_df_sjoined["KOD_GMI"])
    )]

gminas_to_check = accidents_to_correct["KOD_GMI"].dropna().unique()
accidents_to_correct[["ID", "lat", "lon", "JPT_NAZWA_", "GMINA", "JPT_KOD_JE", "KOD_GMI"]]

           ID        lat        lon  JPT_NAZWA_     GMINA JPT_KOD_JE  KOD_GMI
1   106651967  52.228472  20.958278    WARSZAWA  WARSZAWA    1465011  1465011
6   106650103  52.360833  21.626944  STRACHÓWKA  WARSZAWA    1434102  1465011
9   106658062  52.275944  20.951917    WARSZAWA  WARSZAWA    1465011  1465011
10  106650043  52.221611  21.084861    WARSZAWA  WARSZAWA    1465011  1465011
11  106651432  52.203972  21.039222    WARSZAWA  WARSZAWA    1465011  1465011
..        ...        ...        ...         ...       ...        ...      ...
66  124354855  52.227913  21.018236    WARSZAWA  WARSZAWA    1465011  1465011
67  124964206  52.190134  20.959193    WARSZAWA  WARSZAWA    1465011  1465011
68  125740653  52.195588  20.928337    WARSZAWA  WARSZAWA    1465011  1465011
69  125742057  52.240097  21.133210    WARSZAWA  WARSZAWA    1465011  1465011
88  126739726  52.230659  20.984528    WARSZAWA  WARSZAWA    1465011  1465011

[184988 rows x 7 columns]

In [43]:
accidents_to_correct[accidents_to_correct.geometry.is_valid].to_file(r"gis\sewik_suspicious_accidents_locations.shp")

C:\Users\Witold\AppData\Local\Temp\ipykernel_10756\2549667815.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  accidents_to_correct[accidents_to_correct.geometry.is_valid].to_file(r"gis\sewik_suspicious_accidents_locations.shp")
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'DataUtworzenia' to 'DataUtworz'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'SzkicZdarzenia' to 'SzkicZdarz'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'JEDNOSTKA_MIEJSCA' to 'JEDNOSTKA_'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'JEDNOSTKA_LIKWIDUJACA' to 'JEDNOSTK_1'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'JEDNOSTKA_OPERATORA' to 'JEDNOSTK_2'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'MIEJSCOWOSC' to 'MIEJSCOWOS'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'ULICA_ADRES' to 'ULICA_ADRE'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'DATA_ZDARZENIA' to 'DATA_ZDARZ'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'DATA_ZDARZ' to 'DATA_ZDA_1'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'GODZINA_ZDARZ' to 'GODZINA_ZD'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'PREDKOSC_DOPUSZCZALNA' to 'PREDKOSC_D'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'SZOS_TABK_TYPE' to 'SZOS_TABK_'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'SZRD_TABK_TYPE' to 'SZRD_TABK_'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'DROGA_PUBLICZNA' to 'DROGA_PUBL'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'INFO_O_DRODZE' to 'INFO_O_DRO'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'WARUNKI_ATMOSFERYCZNE' to 'WARUNKI_AT'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'INNE_PRZYCZYNY' to 'INNE_PRZYC'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'LICZBA_PASOW' to 'LICZBA_PAS'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'DATA_ZGLOSZENIA' to 'DATA_ZGLOS'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'DATA_PRZYJAZDU' to 'DATA_PRZYJ'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'ULICA_SKRZYZ' to 'ULICA_SKRZ'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'USZKODZENIA_POZA_POJAZDAMI' to 'USZKODZENI'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'RONDO_WEZEL' to 'RONDO_WEZE'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'STREFA_ZAMIESZKALA' to 'STREFA_ZAM'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'ODLEGLOSC_SKRZYZ' to 'ODLEGLOSC_'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'STREFA_RUCHU' to 'STREFA_RUC'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'source_file' to 'source_fil'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'index_right' to 'index_righ'
  ogr_write(

In [54]:
matches = []

# Calculate total number of accidents to process
total_accidents = len(accidents_to_correct)

# Initialize progress bar with ETA
pbar = tqdm(total=total_accidents, desc="Processing accidents")

total_matches = 0
processed_count = 0
last_update = 0

# Process each municipality separately
for kod_gminy in gminas_to_check:
    # Get accidents in this municipality
    gmina = gminy_powiaty.loc[gminy_powiaty["KOD_GMI"] == kod_gminy, "GMINA"].iloc[0]
    gmina_geom = gminy.loc[gminy["JPT_KOD_JE"] == kod_gminy, "geometry"].iloc[0]

    accidents_in_municipality = accidents_to_correct[
        (accidents_to_correct["KOD_GMI"] == kod_gminy) &
        (
            (accidents_to_correct["GMINA"] == "WARSZAWA") | 
            (accidents_to_correct["JPT_KOD_JE"] != accidents_to_correct["KOD_GMI"])
        )
    ]
    
    # Get streets in this municipality
    streets_in_municipality = osm_streets[osm_streets["JPT_KOD_JE"] == kod_gminy]
    adresses_in_municipality = osm_adresses[osm_adresses["JPT_KOD_JE"] == kod_gminy]
    
    if streets_in_municipality.empty:
        # Update progress bar for accidents we can't process
        pbar.update(len(accidents_in_municipality))
        processed_count += len(accidents_in_municipality)
        continue
    
    # Get unique street names for fuzzy matching (keep original case)
    street_names = streets_in_municipality["name"].dropna().unique().tolist()

    if not street_names:
        # Update progress bar for accidents we can't process
        pbar.update(len(accidents_in_municipality))
        processed_count += len(accidents_in_municipality)
        continue
    
    # Match each accident to the best street
    for idx, accident in accidents_in_municipality.iterrows():
        accident_street = accident["ULICA_ADRES"]
        accident_address = accident["NUMER_DOMU"]
        processed_count += 1
        
        # First, let's parse coordinates once for this accident
        coord_y_clean = str(accident["WSP_GPS_Y"]).replace("''","'").replace(',','')
        coord_x_clean = str(accident["WSP_GPS_X"]).replace("''","'").replace(',','')
        
        decimal_lat = parse_as_decimal(coord_y_clean)
        decimal_lon = parse_as_decimal(coord_x_clean)
        degree_lat = parse_as_degrees(coord_y_clean)
        degree_lon = parse_as_degrees(coord_x_clean)

        # Test which coordinate parsing gives better results
        candidate_points = []
        if decimal_lat is not None and decimal_lon is not None:
            candidate_points.append({"point": Point(decimal_lon, decimal_lat), "lat": decimal_lat, "lon": decimal_lon, "type": "decimal", "within_gmina": False})
        if degree_lat is not None and degree_lon is not None:
            candidate_points.append({"point": Point(degree_lon, degree_lat), "lat": degree_lat, "lon": degree_lon, "type": "degree", "within_gmina": False})
        if decimal_lat is not None and degree_lon is not None:
            candidate_points.append({"point": Point(degree_lon, decimal_lat), "lat": decimal_lat, "lon": degree_lon, "type": "decimal_lat_degree_lon", "within_gmina": False})
        if degree_lat is not None and decimal_lon is not None:
            candidate_points.append({"point": Point(decimal_lon, degree_lat), "lat": degree_lat, "lon": decimal_lon, "type": "degree_lat_decimal_lon", "within_gmina": False})

        # Add original coordinates if available
        if not pd.isna(accident["lat"]) and not pd.isna(accident["lon"]):
            candidate_points.append({"point": Point(accident["lon"], accident["lat"]), "lat": accident["lat"], "lon": accident["lon"], "type": "original", "within_gmina": False})

        # check which coordinate is within Gmina
        for coord_candidate in candidate_points:
            coord_candidate["within_gmina"] = gmina_geom.contains(accident["geometry"])
            
        coord_within_gmina = None
        # if candidate_points[-1]["within_gmina"] == False:
        #     if candidate_points[0]["within_gmina"] == True:
        #         coord_within_gmina = candidate_points[0]
        #     if candidate_points[1]["within_gmina"] == True:
        #         coord_within_gmina = candidate_points[1]

        #     if coord_within_gmina is None:
        #         if candidate_points[2]["within_gmina"] == True:
        #             coord_within_gmina = candidate_points[2]
        #         if coord_within_gmina is not None and candidate_points[3]["within_gmina"] == True:
        #             coord_within_gmina = candidate_points[3]

        if pd.isna(accident_street) or accident_street == '':
            # For missing street names, keep current coordinates and create a basic record
            if processed_count - last_update >= 50:
                pbar.update(processed_count - last_update)
                match_pct = (total_matches / processed_count * 100) if processed_count > 0 else 0
                pbar.set_postfix({
                    'matches': total_matches,
                    'match_rate': f'{match_pct:.1f}%'
                })
                last_update = processed_count
            
            # Create record with no street match but keep original coordinates
            match_record = {
                "accident_id": accident["ID"],
                "municipality": gmina,
                "accident_street": None,
                "matched_street": None,
                "similarity_score": None,
                "distance_to_street": None,
                "lat": accident["lat"],
                "lon": accident["lon"],
                "WSP_GPS_X": accident["WSP_GPS_X"],
                "WSP_GPS_Y": accident["WSP_GPS_Y"],
                "accident_geometry": accident["geometry"],
                "street_geometry": None
            }
            matches.append(match_record)
            total_matches += 1
            # if coord_within_gmina is not None:
            #     match_record["best_lat"] = coord_within_gmina["lat"]
            #     match_record["best_lon"] = coord_within_gmina["lon"]
            #     match_record["best_coord_type"] = coord_within_gmina["type"]
            #     match_record["street_geometry"] = None
            #     total_matches += 1

            # continue

        # Find best matching street name (case-insensitive)
        best_street, similarity_score = best_match(accident_street, street_names)

        # Lower minimum threshold but add better validation
        if best_street and similarity_score >= 60:  # Reduced from 75 to 60            
            # Get ALL street segments with this name (case-insensitive search)
            matched_streets = streets_in_municipality[
                streets_in_municipality["name"].str.upper() == str(best_street).upper()]

            # Find the closest street segment geometrically
            accident_point = accident["geometry"]
            best_distance = float('inf')
            closest_street = None
            best_coords = None
            
            for _, street_segment in matched_streets.iterrows():
                # Test all coordinate interpretations against this street segment
                for coord_candidate in candidate_points:
                    distance = coord_candidate["point"].distance(street_segment["geometry"])
                    
                    if distance < best_distance:
                        best_distance = distance
                        best_coords = coord_candidate
                        closest_street = street_segment
            
            # Convert distance to meters for validation (approximate for Poland ~52°N)
            distance_meters = best_distance * 111320
            
            # Only accept matches if they're within reasonable distance (e.g., 500 meters)
            # AND have good similarity score, OR very close distance with moderate similarity
            is_valid_match = False
            
            if distance_meters <= 100 and similarity_score >= 60:  # Very close, moderate similarity OK
                is_valid_match = True
            elif distance_meters <= 200 and similarity_score >= 70:  # Close, good similarity
                is_valid_match = True
            elif distance_meters <= 500 and similarity_score >= 80:  # Moderate distance, high similarity
                is_valid_match = True
            elif similarity_score > 95:  # Almost same
                is_valid_match = True
            match_record = {
                "accident_id": accident["ID"],
                "municipality": gmina,
                "accident_street": accident_street,
                "matched_street": best_street,
                "similarity_score": similarity_score,
                "distance_to_street": best_distance,
                "distance_to_street_meters": distance_meters,
                "WSP_GPS_X": accident["WSP_GPS_X"],
                "WSP_GPS_Y": accident["WSP_GPS_Y"],
                "best_lat": None,
                "best_lon": None,
                "best_coord_type": None,
                "lat": accident["lat"],
                "lon": accident["lon"],
                "accident_geometry": accident["geometry"],
                "street_geometry": None
            }

            if is_valid_match and closest_street is not None:
                match_record["best_lat"] = best_coords["lat"]
                match_record["best_lon"] = best_coords["lon"]
                match_record["best_coord_type"] = best_coords["type"]
                match_record["street_geometry"] = closest_street["geometry"]
                total_matches += 1
                
            matches.append(match_record)

        # Only update progress bar every 50 records
        if processed_count - last_update >= 50:
            pbar.update(processed_count - last_update)
            match_pct = (total_matches / processed_count * 100) if processed_count > 0 else 0
            pbar.set_postfix({
                'matches': total_matches,
                'match_rate': f'{match_pct:.1f}%'
            })
            last_update = processed_count

# Final update for any remaining records
if processed_count > last_update:
    pbar.update(processed_count - last_update)
    match_pct = (total_matches / processed_count * 100) if processed_count > 0 else 0
    pbar.set_postfix({
        'matches': total_matches,
        'match_rate': f'{match_pct:.1f}%'
    })

pbar.close()

# Create final dataframe
final_df = pd.DataFrame(matches)

# Convert distance from degrees to meters (approximate conversion at Poland's latitude)
# 1 degree ≈ 111,320 meters at the equator, but we need to account for latitude
# For Poland (around 52°N), 1 degree longitude ≈ 69,470 meters, 1 degree latitude ≈ 111,320 meters
# We'll use an average approximation for the distance calculation
if len(final_df) > 0:
    # Convert distance from degrees to meters (approximate conversion for Poland's latitude ~52°N)
    # Using Haversine approximation: 1 degree ≈ 111,320 meters
    final_df['distance_to_street_meters'] = final_df['distance_to_street'] * 111320
    
    # Round to 1 decimal place for readability
    final_df['distance_to_street_meters'] = final_df['distance_to_street_meters'].round(1)

print(f"\n" + "="*50)
print(f"FINAL RESULTS:")
print(f"Total matches created: {len(final_df)}")
if len(final_df) > 0:
    print(f"Similarity score distribution:")
    print(final_df["similarity_score"].describe())
    
    print(f"\nDistance to street distribution (meters):")
    print(final_df["distance_to_street_meters"].describe())
    
    # Filter for high-quality matches
    high_quality_matches = final_df[final_df["similarity_score"] >= 80]
    print(f"High quality matches (>= 80% similarity): {len(high_quality_matches)}")
    print(f"Medium quality matches (70-79% similarity): {len(final_df) - len(high_quality_matches)}")
    
    # Show closest matches
    closest_matches = final_df.nsmallest(10, 'distance_to_street_meters')
    print(f"\n10 closest matches:")
    print(closest_matches[['accident_id', 'accident_street', 'matched_street', 'similarity_score', 'distance_to_street_meters']])

Processing accidents:   0%|          | 100/184988 [00:03<1:38:54, 31.15it/s, matches=88, match_rate=88.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   1%|          | 1400/184988 [00:31<1:15:01, 40.78it/s, matches=1259, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   1%|          | 1650/184988 [00:36<1:08:37, 44.53it/s, matches=1474, match_rate=89.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   1%|          | 1900/184988 [00:42<1:11:07, 42.90it/s, matches=1695, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   1%|          | 2200/184988 [00:48<58:37, 51.97it/s, matches=1967, match_rate=89.4%]

Error parsing coordinate '52*11'28/': could not convert string to float: '28/'
Error parsing coordinate '52*11'28/': could not convert string to float: '28/'

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   1%|          | 2250/184988 [00:49<57:59, 52.52it/s, matches=2010, match_rate=89.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   1%|▏         | 2700/184988 [01:00<1:16:30, 39.71it/s, matches=2409, match_rate=89.2%]

Error parsing coordinate '52*25'': object of type 'int' has no len()
Error parsing coordinate '52*25'': object of type 'int' has no len()

Processing accidents:   2%|▏         | 2850/184988 [01:03<1:12:03, 42.13it/s, matches=2533, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   2%|▏         | 2950/184988 [01:05<1:11:24, 42.49it/s, matches=2620, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   2%|▏         | 3100/184988 [01:09<1:10:53, 42.76it/s, matches=2749, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   2%|▏         | 3150/184988 [01:10<1:09:48, 43.41it/s, matches=2790, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   2%|▏         | 3700/184988 [01:22<1:10:00, 43.16it/s, matches=3264, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   2%|▏         | 3800/184988 [01:25<1:18:38, 38.40it/s, matches=3356, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   2%|▏         | 3950/184988 [01:29<1:16:45, 39.31it/s, matches=3488, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   2%|▏         | 4350/184988 [01:39<1:18:07, 38.54it/s, matches=3838, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   3%|▎         | 4700/184988 [01:48<1:16:38, 39.20it/s, matches=4147, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   3%|▎         | 5000/184988 [01:55<1:10:59, 42.25it/s, matches=4414, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   3%|▎         | 5050/184988 [01:56<1:10:21, 42.62it/s, matches=4457, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   3%|▎         | 5700/184988 [02:09<55:33, 53.79it/s, matches=5026, match_rate=88.2%]  C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   3%|▎         | 5750/184988 [02:10<58:38, 50.93it/s, matches=5069, match_rate=88.2%]

Error parsing coordinate '`5*21'526': could not convert string to float: '`5'
Error parsing coordinate '`5*21'526': could not convert string to float: '`5'

Processing accidents:   3%|▎         | 5900/184988 [02:14<1:03:22, 47.10it/s, matches=5202, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   3%|▎         | 6050/184988 [02:17<59:21, 50.25it/s, matches=5329, match_rate=88.1%]  C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   3%|▎         | 6200/184988 [02:20<58:55, 50.57it/s, matches=5461, match_rate=88.1%]  C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   4%|▎         | 6650/184988 [02:29<57:54, 51.33it/s, matches=5848, match_rate=87.9%]  C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   4%|▍         | 7000/184988 [02:35<57:24, 51.67it/s, matches=6169, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   4%|▍         | 7100/184988 [02:37<56:08, 52.81it/s, matches=6256, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   4%|▍         | 7850/184988 [02:52<55:52, 52.83it/s, matches=6917, match_rate=88.1%]  C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   4%|▍         | 7900/184988 [02:53<54:15, 54.40it/s, matches=6957, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   4%|▍         | 8100/184988 [02:57<58:09, 50.69it/s, matches=7135, match_rate=88.1%]  C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   4%|▍         | 8250/184988 [03:00<57:40, 51.07it/s, matches=7273, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   5%|▍         | 8450/184988 [03:04<54:42, 53.79it/s, matches=7442, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   5%|▍         | 8600/184988 [03:06<53:12, 55.25it/s, matches=7579, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   5%|▍         | 8650/184988 [03:07<51:39, 56.89it/s, matches=7624, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   5%|▍         | 9050/184988 [03:16<1:03:41, 46.04it/s, matches=7979, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   5%|▍         | 9150/184988 [03:18<1:02:28, 46.90it/s, matches=8062, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   5%|▍         | 9200/184988 [03:19<1:01:31, 47.62it/s, matches=8105, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   5%|▌         | 9250/184988 [03:20<1:01:45, 47.43it/s, matches=8148, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   5%|▌         | 9450/184988 [03:24<1:03:34, 46.02it/s, matches=8325, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   5%|▌         | 9750/184988 [03:31<1:07:45, 43.11it/s, matches=8584, match_rate=88.0%]

Error parsing coordinate '21*00'5'8': could not convert string to float: "5'8"
Error parsing coordinate '21*00'5'8': could not convert string to float: "5'8"

Processing accidents:   5%|▌         | 9850/184988 [03:33<1:04:00, 45.60it/s, matches=8676, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   6%|▌         | 10400/184988 [03:45<1:04:48, 44.89it/s, matches=9165, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   6%|▌         | 10550/184988 [03:48<1:04:14, 45.25it/s, matches=9293, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   6%|▌         | 10650/184988 [03:50<1:00:58, 47.65it/s, matches=9383, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   6%|▌         | 10750/184988 [03:53<1:02:09, 46.72it/s, matches=9477, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   6%|▌         | 10800/184988 [03:54<1:05:02, 44.64it/s, matches=9519, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   6%|▌         | 10850/184988 [03:55<1:05:42, 44.17it/s, matches=9562, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   6%|▌         | 10900/184988 [03:56<1:06:37, 43.55it/s, matches=9607, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   6%|▌         | 10950/184988 [03:57<1:08:16, 42.49it/s, matches=9653, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   6%|▌         | 11000/184988 [03:59<1:06:04, 43.89it/s, matches=9692, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   6%|▌         | 11050/184988 [04:00<1:07:05, 43.20it/s, matches=9737, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   6%|▌         | 11100/184988 [04:01<1:07:03, 43.21it/s, matches=9778, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   6%|▌         | 11150/184988 [04:02<1:07:26, 42.96it/s, matches=9819, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   6%|▌         | 11250/184988 [04:04<1:01:10, 47.33it/s, matches=9908, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   6%|▌         | 11550/184988 [04:10<57:24, 50.35it/s, matches=10166, match_rate=88.0%] C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   6%|▋         | 11700/184988 [04:13<58:13, 49.60it/s, matches=10299, match_rate=88.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)

Error parsing coordinate '21*15'': object of type 'int' has no len()
Error parsing coordinate '21*15'': object of type 'int' has no len()

Processing accidents:   6%|▋         | 11800/184988 [04:15<59:22, 48.61it/s, matches=10387, match_rate=88.0%]

Error parsing coordinate '52*14'1-1': could not convert string to float: '1-1'
Error parsing coordinate '52*14'1-1': could not convert string to float: '1-1'

Processing accidents:   6%|▋         | 11900/184988 [04:17<59:07, 48.80it/s, matches=10473, match_rate=88.0%]  C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   6%|▋         | 11950/184988 [04:18<58:28, 49.32it/s, matches=10513, match_rate=88.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   7%|▋         | 12100/184988 [04:21<1:01:23, 46.93it/s, matches=10646, match_rate=88.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   7%|▋         | 12150/184988 [04:22<1:02:26, 46.14it/s, matches=10692, match_rate=88.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   7%|▋         | 12200/184988 [04:23<59:05, 48.73it/s, matches=10733, match_rate=88.0%]  C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   7%|▋         | 12250/184988 [04:24<58:35, 49.14it/s, matches=10778, match_rate=88.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   7%|▋         | 12300/184988 [04:25<56:06, 51.29it/s, matches=10821, match_rate=88.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   7%|▋         | 12400/184988 [04:27<56:47, 50.65it/s, matches=10906, match_rate=88.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   7%|▋         | 12500/184988 [04:29<56:29, 50.90it/s, matches=10996, match_rate=88.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   7%|▋         | 12750/184988 [04:35<1:03:06, 45.49it/s, matches=11220, match_rate=88.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   7%|▋         | 12800/184988 [04:36<1:01:00, 47.03it/s, matches=11266, match_rate=88.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   7%|▋         | 12950/184988 [04:39<58:05, 49.36it/s, matches=11394, match_rate=88.0%]  C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   7%|▋         | 13050/184988 [04:41<56:54, 50.35it/s, matches=11480, match_rate=88.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   7%|▋         | 13100/184988 [04:42<56:09, 51.01it/s, matches=11528, match_rate=88.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   7%|▋         | 13150/184988 [04:43<56:36, 50.59it/s, matches=11572, match_rate=88.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   7%|▋         | 13250/184988 [04:45<56:16, 50.87it/s, matches=11659, match_rate=88.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   7%|▋         | 13450/184988 [04:48<54:48, 52.16it/s, matches=11822, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   7%|▋         | 13500/184988 [04:49<54:55, 52.04it/s, matches=11870, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   7%|▋         | 13600/184988 [04:51<54:43, 52.20it/s, matches=11956, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   7%|▋         | 13750/184988 [04:54<55:22, 51.54it/s, matches=12087, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   7%|▋         | 13800/184988 [04:55<52:38, 54.20it/s, matches=12131, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   7%|▋         | 13850/184988 [04:56<52:51, 53.95it/s, matches=12174, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   8%|▊         | 13900/184988 [04:57<52:57, 53.84it/s, matches=12215, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   8%|▊         | 14000/184988 [04:59<56:07, 50.77it/s, matches=12301, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   8%|▊         | 14100/184988 [05:01<55:07, 51.66it/s, matches=12390, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   8%|▊         | 14150/184988 [05:02<54:09, 52.57it/s, matches=12434, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   8%|▊         | 14250/184988 [05:04<57:06, 49.84it/s, matches=12522, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   8%|▊         | 14400/184988 [05:07<55:39, 51.08it/s, matches=12665, match_rate=88.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   8%|▊         | 14450/184988 [05:08<54:39, 52.01it/s, matches=12709, match_rate=88.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   8%|▊         | 14600/184988 [05:11<53:45, 52.83it/s, matches=12840, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   8%|▊         | 14650/184988 [05:11<53:00, 53.55it/s, matches=12887, match_rate=88.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   8%|▊         | 15300/184988 [05:24<52:14, 54.13it/s, matches=13475, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   8%|▊         | 15350/184988 [05:25<54:55, 51.47it/s, matches=13516, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   8%|▊         | 15400/184988 [05:26<54:25, 51.94it/s, matches=13564, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   8%|▊         | 15550/184988 [05:29<51:27, 54.87it/s, matches=13695, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   8%|▊         | 15650/184988 [05:31<59:23, 47.52it/s, matches=13781, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   9%|▊         | 15750/184988 [05:34<1:00:10, 46.87it/s, matches=13869, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   9%|▉         | 16400/184988 [05:47<55:31, 50.60it/s, matches=14443, match_rate=88.1%]  C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   9%|▉         | 16600/184988 [05:51<59:13, 47.39it/s, matches=14627, match_rate=88.1%]  C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)

Error parsing coordinate '52*''237': could not convert string to float: ''
Error parsing coordinate '52*''237': could not convert string to float: ''

Processing accidents:   9%|▉         | 17250/184988 [06:05<56:28, 49.51it/s, matches=15202, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:   9%|▉         | 17500/184988 [06:10<54:52, 50.88it/s, matches=15425, match_rate=88.1%]

Error parsing coordinate '21*'1'17': could not convert string to float: ''
Error parsing coordinate '21*'1'17': could not convert string to float: ''

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  10%|▉         | 17600/184988 [06:12<55:25, 50.33it/s, matches=15515, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  10%|▉         | 17650/184988 [06:13<55:28, 50.27it/s, matches=15558, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  10%|▉         | 17750/184988 [06:14<54:53, 50.78it/s, matches=15643, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  10%|▉         | 17800/184988 [06:15<54:00, 51.59it/s, matches=15687, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  10%|▉         | 17900/184988 [06:17<54:18, 51.28it/s, matches=15775, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  10%|▉         | 18150/184988 [06:22<54:23, 51.12it/s, matches=15998, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  10%|▉         | 18200/184988 [06:23<53:48, 51.66it/s, matches=16044, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  10%|▉         | 18250/184988 [06:24<53:51, 51.60it/s, matches=16090, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  10%|█         | 18750/184988 [06:34<52:36, 52.67it/s, matches=16540, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  10%|█         | 18850/184988 [06:36<55:46, 49.64it/s, matches=16630, match_rate=88.2%]

Error parsing coordinate '52*27'': object of type 'int' has no len()
Error parsing coordinate '52*27'': object of type 'int' has no len()

Processing accidents:  10%|█         | 19150/184988 [06:42<51:54, 53.24it/s, matches=16892, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  10%|█         | 19250/184988 [06:44<56:38, 48.77it/s, matches=16982, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  10%|█         | 19400/184988 [06:47<54:58, 50.20it/s, matches=17119, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  11%|█         | 19550/184988 [06:50<55:16, 49.88it/s, matches=17240, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  11%|█         | 19700/184988 [06:53<59:35, 46.23it/s, matches=17370, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)

Error parsing coordinate '20*98'': object of type 'int' has no len()
Error parsing coordinate '20*98'': object of type 'int' has no len()

Processing accidents:  11%|█         | 20050/184988 [07:00<49:46, 55.23it/s, matches=17675, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  11%|█         | 20100/184988 [07:01<51:08, 53.73it/s, matches=17722, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  11%|█         | 20350/184988 [07:05<50:36, 54.23it/s, matches=17938, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  11%|█         | 20500/184988 [07:08<53:00, 51.72it/s, matches=18068, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  11%|█         | 20550/184988 [07:09<51:52, 52.83it/s, matches=18114, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  11%|█         | 20600/184988 [07:10<51:21, 53.35it/s, matches=18155, match_rate=88.1%]

Error parsing coordinate '21*'4'041': could not convert string to float: ''
Error parsing coordinate '21*'4'041': could not convert string to float: ''

Processing accidents:  11%|█         | 20700/184988 [07:12<51:47, 52.86it/s, matches=18246, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  11%|█         | 20800/184988 [07:14<52:29, 52.14it/s, matches=18337, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  11%|█▏        | 21100/184988 [07:20<55:04, 49.59it/s, matches=18602, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  12%|█▏        | 21400/184988 [07:26<55:56, 48.74it/s, matches=18866, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  12%|█▏        | 21600/184988 [07:30<56:43, 48.01it/s, matches=19043, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  12%|█▏        | 21850/184988 [07:35<53:54, 50.44it/s, matches=19261, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  12%|█▏        | 21950/184988 [07:37<56:51, 47.79it/s, matches=19351, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  12%|█▏        | 22100/184988 [07:40<57:19, 47.35it/s, matches=19480, match_rate=88.1%]  C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  12%|█▏        | 22300/184988 [07:44<51:38, 52.50it/s, matches=19654, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  12%|█▏        | 22900/184988 [07:58<1:02:07, 43.48it/s, matches=20194, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  12%|█▏        | 22950/184988 [07:59<1:01:22, 44.01it/s, matches=20239, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  13%|█▎        | 23150/184988 [08:03<56:56, 47.36it/s, matches=20409, match_rate=88.2%]  C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  13%|█▎        | 23200/184988 [08:04<57:53, 46.58it/s, matches=20450, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  13%|█▎        | 23250/184988 [08:05<57:30, 46.87it/s, matches=20497, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  13%|█▎        | 23300/184988 [08:06<55:29, 48.56it/s, matches=20540, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  13%|█▎        | 23400/184988 [08:08<52:53, 50.92it/s, matches=20621, match_rate=88.1%]

Error parsing coordinate '21*08'': object of type 'int' has no len()
Error parsing coordinate '21*08'': object of type 'int' has no len()

Processing accidents:  13%|█▎        | 23450/184988 [08:09<58:16, 46.20it/s, matches=20666, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  13%|█▎        | 23500/184988 [08:10<55:06, 48.85it/s, matches=20709, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  13%|█▎        | 23700/184988 [08:14<49:43, 54.06it/s, matches=20886, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  13%|█▎        | 23800/184988 [08:15<48:10, 55.77it/s, matches=20977, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  13%|█▎        | 24150/184988 [08:23<56:14, 47.67it/s, matches=21289, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  13%|█▎        | 24200/184988 [08:24<55:48, 48.02it/s, matches=21330, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  13%|█▎        | 24350/184988 [08:27<55:26, 48.29it/s, matches=21466, match_rate=88.2%]

Error parsing coordinate '\2*10'241': could not convert string to float: '\\2'
Error parsing coordinate '\2*10'241': could not convert string to float: '\\2'

Processing accidents:  13%|█▎        | 24400/184988 [08:28<53:46, 49.77it/s, matches=21503, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  13%|█▎        | 24500/184988 [08:30<50:59, 52.45it/s, matches=21592, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  13%|█▎        | 24800/184988 [08:36<49:45, 53.65it/s, matches=21855, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  13%|█▎        | 24850/184988 [08:36<49:16, 54.17it/s, matches=21897, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  14%|█▎        | 25050/184988 [08:40<52:33, 50.72it/s, matches=22080, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  14%|█▎        | 25100/184988 [08:41<52:16, 50.98it/s, matches=22121, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  14%|█▎        | 25150/184988 [08:42<52:36, 50.64it/s, matches=22168, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  14%|█▎        | 25300/184988 [08:46<53:27, 49.79it/s, matches=22300, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  14%|█▎        | 25350/184988 [08:46<53:05, 50.11it/s, matches=22337, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  14%|█▍        | 25500/184988 [08:49<53:30, 49.67it/s, matches=22474, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  14%|█▍        | 25550/184988 [08:51<54:33, 48.71it/s, matches=22518, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  14%|█▍        | 25750/184988 [08:54<53:33, 49.55it/s, matches=22693, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  14%|█▍        | 25800/184988 [08:55<53:17, 49.79it/s, matches=22733, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  14%|█▍        | 25850/184988 [08:56<53:55, 49.19it/s, matches=22775, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  14%|█▍        | 26000/184988 [08:59<51:05, 51.86it/s, matches=22906, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  14%|█▍        | 26200/184988 [09:03<53:07, 49.82it/s, matches=23086, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  14%|█▍        | 26300/184988 [09:05<54:03, 48.92it/s, matches=23170, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  14%|█▍        | 26350/184988 [09:07<56:43, 46.61it/s, matches=23215, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  14%|█▍        | 26400/184988 [09:08<55:33, 47.57it/s, matches=23257, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  14%|█▍        | 26450/184988 [09:09<54:30, 48.48it/s, matches=23300, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  14%|█▍        | 26500/184988 [09:09<52:08, 50.66it/s, matches=23343, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  14%|█▍        | 26550/184988 [09:11<52:29, 50.30it/s, matches=23389, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  14%|█▍        | 26700/184988 [09:13<52:16, 50.47it/s, matches=23524, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  15%|█▍        | 26950/184988 [09:19<54:40, 48.17it/s, matches=23746, match_rate=88.1%]

Error parsing coordinate '52*21'': object of type 'int' has no len()
Error parsing coordinate '52*21'': object of type 'int' has no len()

Processing accidents:  15%|█▍        | 27000/184988 [09:20<52:30, 50.14it/s, matches=23789, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  15%|█▍        | 27050/184988 [09:21<54:43, 48.10it/s, matches=23836, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  15%|█▍        | 27450/184988 [09:29<53:06, 49.44it/s, matches=24188, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  15%|█▍        | 27500/184988 [09:30<52:58, 49.55it/s, matches=24235, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  15%|█▌        | 27850/184988 [09:36<50:29, 51.86it/s, matches=24545, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  15%|█▌        | 27900/184988 [09:37<52:57, 49.44it/s, matches=24589, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  15%|█▌        | 28050/184988 [09:40<49:55, 52.39it/s, matches=24723, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  15%|█▌        | 28100/184988 [09:41<50:47, 51.48it/s, matches=24764, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  15%|█▌        | 28150/184988 [09:42<52:56, 49.37it/s, matches=24809, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  15%|█▌        | 28300/184988 [09:46<56:22, 46.32it/s, matches=24948, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  15%|█▌        | 28450/184988 [09:49<59:37, 43.75it/s, matches=25084, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  15%|█▌        | 28500/184988 [09:50<59:53, 43.55it/s, matches=25124, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  15%|█▌        | 28600/184988 [09:53<59:13, 44.01it/s, matches=25214, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  15%|█▌        | 28650/184988 [09:54<58:08, 44.81it/s, matches=25260, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  16%|█▌        | 28800/184988 [09:57<57:30, 45.27it/s, matches=25396, match_rate=88.2%]

Error parsing coordinate '52*80'': object of type 'int' has no len()
Error parsing coordinate '52*80'': object of type 'int' has no len()

Processing accidents:  16%|█▌        | 29250/184988 [10:07<55:56, 46.40it/s, matches=25786, match_rate=88.2%]  C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  16%|█▌        | 29400/184988 [10:10<54:22, 47.69it/s, matches=25914, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  16%|█▌        | 29450/184988 [10:11<54:42, 47.38it/s, matches=25957, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  16%|█▌        | 29550/184988 [10:13<52:39, 49.20it/s, matches=26046, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  16%|█▌        | 29650/184988 [10:15<51:03, 50.71it/s, matches=26134, match_rate=88.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  16%|█▌        | 29900/184988 [10:20<51:02, 50.65it/s, matches=26365, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  16%|█▌        | 30050/184988 [10:23<53:49, 47.97it/s, matches=26502, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  16%|█▋        | 30150/184988 [10:25<53:06, 48.59it/s, matches=26587, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  16%|█▋        | 30400/184988 [10:31<56:06, 45.91it/s, matches=26806, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  16%|█▋        | 30450/184988 [10:32<57:59, 44.41it/s, matches=26845, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)

Error parsing coordinate '21*'2'45': could not convert string to float: ''
Error parsing coordinate '21*'2'45': could not convert string to float: ''

Processing accidents:  17%|█▋        | 30800/184988 [10:39<53:06, 48.38it/s, matches=27161, match_rate=88.2%]

Error parsing coordinate '21*07'': object of type 'int' has no len()
Error parsing coordinate '21*07'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  17%|█▋        | 30850/184988 [10:40<50:50, 50.54it/s, matches=27205, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  17%|█▋        | 31100/184988 [10:45<55:09, 46.49it/s, matches=27427, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  17%|█▋        | 31200/184988 [10:47<56:34, 45.31it/s, matches=27517, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  17%|█▋        | 31550/184988 [10:55<54:28, 46.95it/s, matches=27833, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  17%|█▋        | 31800/184988 [11:00<48:22, 52.77it/s, matches=28061, match_rate=88.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  17%|█▋        | 32350/184988 [11:10<50:03, 50.82it/s, matches=28560, match_rate=88.3%]

Error parsing coordinate '21*28'': object of type 'int' has no len()
Error parsing coordinate '21*28'': object of type 'int' has no len()

Processing accidents:  18%|█▊        | 32400/184988 [11:11<50:51, 50.00it/s, matches=28604, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  18%|█▊        | 32450/184988 [11:12<52:44, 48.20it/s, matches=28644, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  18%|█▊        | 32850/184988 [11:21<53:22, 47.51it/s, matches=29014, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  18%|█▊        | 32900/184988 [11:22<53:02, 47.79it/s, matches=29057, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  18%|█▊        | 33500/184988 [11:35<55:01, 45.88it/s, matches=29587, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  18%|█▊        | 33750/184988 [11:41<56:45, 44.41it/s, matches=29810, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  18%|█▊        | 33800/184988 [11:42<57:28, 43.84it/s, matches=29854, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  18%|█▊        | 33850/184988 [11:43<56:32, 44.55it/s, matches=29900, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  18%|█▊        | 33950/184988 [11:45<54:29, 46.19it/s, matches=3e+4, match_rate=88.3%] C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  18%|█▊        | 34000/184988 [11:46<54:04, 46.54it/s, matches=3e+4, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  18%|█▊        | 34050/184988 [11:47<53:47, 46.76it/s, matches=30073, match_rate=88.3%]

Error parsing coordinate 'N5*20'736': could not convert string to float: 'N5'
Error parsing coordinate 'N5*20'736': could not convert string to float: 'N5'

Processing accidents:  18%|█▊        | 34100/184988 [11:49<53:29, 47.02it/s, matches=30120, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  19%|█▊        | 34250/184988 [11:52<54:26, 46.14it/s, matches=30259, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  19%|█▊        | 34300/184988 [11:53<55:49, 44.99it/s, matches=30303, match_rate=88.3%]

Error parsing coordinate '21*09'': object of type 'int' has no len()
Error parsing coordinate '21*09'': object of type 'int' has no len()

Processing accidents:  19%|█▊        | 34550/184988 [11:58<54:09, 46.30it/s, matches=30517, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  19%|█▊        | 34600/184988 [12:00<55:35, 45.09it/s, matches=30563, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  19%|█▊        | 34650/184988 [12:01<55:32, 45.11it/s, matches=30605, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  19%|█▉        | 34700/184988 [12:02<56:03, 44.68it/s, matches=30650, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  19%|█▉        | 34750/184988 [12:03<1:00:29, 41.40it/s, matches=30696, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  19%|█▉        | 35100/184988 [12:11<57:29, 43.45it/s, matches=31008, match_rate=88.3%]  C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  19%|█▉        | 35850/184988 [12:26<49:57, 49.76it/s, matches=31692, match_rate=88.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  19%|█▉        | 35950/184988 [12:28<48:34, 51.14it/s, matches=31782, match_rate=88.4%]

Error parsing coordinate '52*86'': object of type 'int' has no len()
Error parsing coordinate '52*86'': object of type 'int' has no len()

Processing accidents:  20%|█▉        | 36300/184988 [12:35<49:41, 49.87it/s, matches=32098, match_rate=88.4%]

Error parsing coordinate '21*54'': object of type 'int' has no len()
Error parsing coordinate '21*54'': object of type 'int' has no len()

Processing accidents:  20%|█▉        | 36400/184988 [12:37<53:06, 46.63it/s, matches=32181, match_rate=88.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  20%|█▉        | 36500/184988 [12:39<50:09, 49.33it/s, matches=32273, match_rate=88.4%]

Error parsing coordinate '21*03'': object of type 'int' has no len()
Error parsing coordinate '21*03'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  20%|█▉        | 36600/184988 [12:41<49:20, 50.12it/s, matches=32366, match_rate=88.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  20%|█▉        | 36700/184988 [12:43<47:35, 51.93it/s, matches=32456, match_rate=88.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  20%|█▉        | 36750/184988 [12:44<46:11, 53.49it/s, matches=32502, match_rate=88.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  20%|██        | 37650/184988 [13:01<46:58, 52.28it/s, matches=33316, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  20%|██        | 37900/184988 [13:06<49:37, 49.39it/s, matches=33549, match_rate=88.5%]

Error parsing coordinate '21*1"'57': could not convert string to float: '1"'
Error parsing coordinate '21*1"'57': could not convert string to float: '1"'

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  21%|██        | 37950/184988 [13:07<50:26, 48.59it/s, matches=33592, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  21%|██        | 38000/184988 [13:08<50:58, 48.05it/s, matches=33638, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  21%|██        | 38550/184988 [13:20<53:09, 45.92it/s, matches=34139, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  21%|██        | 38850/184988 [13:26<47:44, 51.03it/s, matches=34406, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  21%|██        | 38900/184988 [13:27<47:03, 51.73it/s, matches=34452, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  21%|██        | 38950/184988 [13:28<47:00, 51.79it/s, matches=34497, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  21%|██        | 39000/184988 [13:29<47:38, 51.07it/s, matches=34540, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  21%|██        | 39050/184988 [13:30<46:45, 52.03it/s, matches=34584, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  21%|██        | 39100/184988 [13:30<46:06, 52.73it/s, matches=34632, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  21%|██        | 39150/184988 [13:31<45:36, 53.30it/s, matches=34675, match_rate=88.6%]

Error parsing coordinate '21*12'': object of type 'int' has no len()
Error parsing coordinate '21*12'': object of type 'int' has no len()

Processing accidents:  21%|██        | 39200/184988 [13:32<45:05, 53.88it/s, matches=34717, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  21%|██▏       | 39400/184988 [13:36<45:18, 53.56it/s, matches=34898, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  22%|██▏       | 39900/184988 [13:46<49:15, 49.09it/s, matches=35356, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  22%|██▏       | 40500/184988 [13:57<47:34, 50.62it/s, matches=35899, match_rate=88.6%]

Error parsing coordinate '21*13'': object of type 'int' has no len()
Error parsing coordinate '21*13'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  22%|██▏       | 40600/184988 [13:59<47:29, 50.67it/s, matches=35988, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  22%|██▏       | 41200/184988 [14:12<52:22, 45.75it/s, matches=36524, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  22%|██▏       | 41250/184988 [14:13<51:43, 46.31it/s, matches=36569, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  22%|██▏       | 41400/184988 [14:16<51:21, 46.60it/s, matches=36693, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  22%|██▏       | 41600/184988 [14:20<51:04, 46.78it/s, matches=36878, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  23%|██▎       | 41750/184988 [14:24<54:06, 44.12it/s, matches=37016, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  23%|██▎       | 41800/184988 [14:25<53:39, 44.47it/s, matches=37062, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  23%|██▎       | 42200/184988 [14:33<50:39, 46.98it/s, matches=37425, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  23%|██▎       | 42250/184988 [14:34<50:15, 47.33it/s, matches=37468, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  23%|██▎       | 42300/184988 [14:35<50:32, 47.05it/s, matches=37513, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  23%|██▎       | 42350/184988 [14:36<50:01, 47.53it/s, matches=37557, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  23%|██▎       | 42550/184988 [14:40<46:02, 51.55it/s, matches=37733, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  23%|██▎       | 43250/184988 [14:54<48:49, 48.38it/s, matches=38376, match_rate=88.7%]

Error parsing coordinate '21*10'6'9': could not convert string to float: "6'9"
Error parsing coordinate '21*10'6'9': could not convert string to float: "6'9"

Processing accidents:  24%|██▎       | 43600/184988 [15:01<42:51, 54.98it/s, matches=38698, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  24%|██▎       | 43650/184988 [15:02<43:56, 53.61it/s, matches=38742, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  24%|██▎       | 43700/184988 [15:03<44:14, 53.22it/s, matches=38786, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  24%|██▎       | 43850/184988 [15:05<42:43, 55.06it/s, matches=38910, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  24%|██▍       | 44050/184988 [15:09<46:51, 50.12it/s, matches=39089, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  24%|██▍       | 44100/184988 [15:10<46:56, 50.02it/s, matches=39136, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  24%|██▍       | 44150/184988 [15:11<46:04, 50.94it/s, matches=39180, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  24%|██▍       | 44300/184988 [15:15<49:14, 47.62it/s, matches=39320, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  24%|██▍       | 44450/184988 [15:17<45:38, 51.33it/s, matches=39465, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  24%|██▍       | 44600/184988 [15:20<47:28, 49.29it/s, matches=39603, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  24%|██▍       | 45150/184988 [15:31<43:26, 53.66it/s, matches=40099, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  25%|██▍       | 45400/184988 [15:36<45:30, 51.12it/s, matches=40316, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  25%|██▍       | 45450/184988 [15:37<44:50, 51.86it/s, matches=40360, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  25%|██▍       | 45600/184988 [15:40<47:05, 49.32it/s, matches=40498, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  25%|██▍       | 45900/184988 [15:47<48:46, 47.52it/s, matches=40782, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  25%|██▍       | 46150/184988 [15:52<46:03, 50.25it/s, matches=41012, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  25%|██▌       | 46300/184988 [15:54<42:07, 54.88it/s, matches=41150, match_rate=88.9%]

Error parsing coordinate '21*00'': object of type 'int' has no len()
Error parsing coordinate '21*00'': object of type 'int' has no len()

Processing accidents:  25%|██▌       | 46850/184988 [16:05<45:24, 50.70it/s, matches=41652, match_rate=88.9%]

Error parsing coordinate '52*15'': object of type 'int' has no len()
Error parsing coordinate '52*15'': object of type 'int' has no len()

Processing accidents:  25%|██▌       | 47150/184988 [16:11<46:06, 49.82it/s, matches=41933, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  26%|██▌       | 47650/184988 [16:21<43:45, 52.32it/s, matches=42398, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  26%|██▌       | 47900/184988 [16:26<46:58, 48.64it/s, matches=42633, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  26%|██▌       | 48150/184988 [16:32<50:09, 45.47it/s, matches=42864, match_rate=89.0%]

Error parsing coordinate '21*'5'81': could not convert string to float: ''
Error parsing coordinate '21*'5'81': could not convert string to float: ''

Processing accidents:  26%|██▌       | 48200/184988 [16:33<49:45, 45.81it/s, matches=42911, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  26%|██▌       | 48350/184988 [16:36<48:40, 46.79it/s, matches=43050, match_rate=89.0%]

Error parsing coordinate '52*70'': object of type 'int' has no len()
Error parsing coordinate '21*13'': object of type 'int' has no len()
Error parsing coordinate '52*70'': object of type 'int' has no len()
Error parsing coordinate '21*13'': object of type 'int' has no len()

Processing accidents:  26%|██▌       | 48450/184988 [16:38<48:05, 47.31it/s, matches=43143, match_rate=89.0%]

Error parsing coordinate '21*16'': object of type 'int' has no len()
Error parsing coordinate '21*16'': object of type 'int' has no len()

Processing accidents:  26%|██▋       | 48900/184988 [16:47<45:57, 49.35it/s, matches=43560, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  27%|██▋       | 49300/184988 [16:55<44:10, 51.20it/s, matches=43928, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  27%|██▋       | 50000/184988 [17:09<51:16, 43.87it/s, matches=44563, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  27%|██▋       | 50600/184988 [17:22<48:04, 46.59it/s, matches=45116, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  27%|██▋       | 50850/184988 [17:27<43:31, 51.37it/s, matches=45343, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  28%|██▊       | 50900/184988 [17:28<45:15, 49.38it/s, matches=45388, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  28%|██▊       | 50950/184988 [17:30<46:51, 47.68it/s, matches=45433, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  28%|██▊       | 51250/184988 [17:36<50:48, 43.87it/s, matches=45702, match_rate=89.2%]

Error parsing coordinate '20*58'3'3': could not convert string to float: "3'3"
Error parsing coordinate '20*58'3'3': could not convert string to float: "3'3"

Processing accidents:  28%|██▊       | 51600/184988 [17:45<56:38, 39.25it/s, matches=46026, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  28%|██▊       | 51850/184988 [17:51<53:48, 41.23it/s, matches=46256, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  28%|██▊       | 52350/184988 [18:01<43:42, 50.58it/s, matches=46707, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  28%|██▊       | 52700/184988 [18:08<43:10, 51.07it/s, matches=47025, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  29%|██▊       | 52800/184988 [18:10<45:08, 48.80it/s, matches=47114, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  29%|██▊       | 52900/184988 [18:12<45:02, 48.87it/s, matches=47203, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  30%|██▉       | 54850/184988 [18:50<38:25, 56.43it/s, matches=48969, match_rate=89.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  30%|██▉       | 55300/184988 [18:59<40:52, 52.87it/s, matches=49373, match_rate=89.3%]

Error parsing coordinate '21*16'': object of type 'int' has no len()
Error parsing coordinate '21*16'': object of type 'int' has no len()

Processing accidents:  30%|██▉       | 55400/184988 [19:01<43:13, 49.97it/s, matches=49469, match_rate=89.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  30%|███       | 55550/184988 [19:04<47:07, 45.77it/s, matches=49601, match_rate=89.3%]

Error parsing coordinate '52*15'': object of type 'int' has no len()
Error parsing coordinate '52*15'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  30%|███       | 55650/184988 [19:06<44:24, 48.54it/s, matches=49694, match_rate=89.3%]

Error parsing coordinate '21*19'': object of type 'int' has no len()
Error parsing coordinate '21*19'': object of type 'int' has no len()

Processing accidents:  30%|███       | 56000/184988 [19:14<49:29, 43.44it/s, matches=5e+4, match_rate=89.3%] C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  30%|███       | 56250/184988 [19:19<45:37, 47.03it/s, matches=50238, match_rate=89.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  30%|███       | 56400/184988 [19:23<46:42, 45.88it/s, matches=50376, match_rate=89.3%]

Error parsing coordinate '21*04'': object of type 'int' has no len()
Error parsing coordinate '21*04'': object of type 'int' has no len()

Processing accidents:  31%|███       | 56450/184988 [19:24<45:41, 46.88it/s, matches=50424, match_rate=89.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  31%|███       | 57050/184988 [19:37<47:42, 44.70it/s, matches=50964, match_rate=89.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  31%|███       | 57100/184988 [19:38<46:15, 46.08it/s, matches=51006, match_rate=89.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  31%|███       | 57250/184988 [19:41<44:32, 47.79it/s, matches=51145, match_rate=89.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  31%|███       | 57350/184988 [19:43<42:31, 50.03it/s, matches=51234, match_rate=89.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)

Error parsing coordinate '21*99'': object of type 'int' has no len()
Error parsing coordinate '21*99'': object of type 'int' has no len()

Processing accidents:  31%|███       | 57500/184988 [19:46<40:23, 52.60it/s, matches=51368, match_rate=89.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  31%|███       | 57550/184988 [19:47<40:50, 52.00it/s, matches=51413, match_rate=89.3%]

Error parsing coordinate '21*06'': object of type 'int' has no len()
Error parsing coordinate '21*06'': object of type 'int' has no len()

Processing accidents:  31%|███       | 57600/184988 [19:48<40:57, 51.84it/s, matches=51457, match_rate=89.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  31%|███       | 57650/184988 [19:49<41:06, 51.63it/s, matches=51499, match_rate=89.3%]

Error parsing coordinate '21*06'': object of type 'int' has no len()
Error parsing coordinate '21*06'': object of type 'int' has no len()

Processing accidents:  31%|███▏      | 57900/184988 [19:54<43:10, 49.06it/s, matches=51734, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  32%|███▏      | 58450/184988 [20:05<45:58, 45.88it/s, matches=52240, match_rate=89.4%]

Error parsing coordinate '21*14'': object of type 'int' has no len()
Error parsing coordinate '21*14'': object of type 'int' has no len()

Processing accidents:  32%|███▏      | 58500/184988 [20:06<44:50, 47.02it/s, matches=52285, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  32%|███▏      | 58850/184988 [20:13<43:10, 48.69it/s, matches=52605, match_rate=89.4%]

Error parsing coordinate '21*12'': object of type 'int' has no len()
Error parsing coordinate '21*12'': object of type 'int' has no len()

Processing accidents:  32%|███▏      | 59000/184988 [20:16<45:22, 46.28it/s, matches=52745, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  32%|███▏      | 59150/184988 [20:20<43:17, 48.45it/s, matches=52883, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  32%|███▏      | 59400/184988 [20:25<43:35, 48.03it/s, matches=53113, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  32%|███▏      | 59500/184988 [20:27<41:59, 49.81it/s, matches=53202, match_rate=89.4%]

Error parsing coordinate '21*29'': object of type 'int' has no len()
Error parsing coordinate '21*29'': object of type 'int' has no len()

Processing accidents:  32%|███▏      | 59750/184988 [20:32<40:52, 51.07it/s, matches=53436, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  32%|███▏      | 60100/184988 [20:40<47:22, 43.94it/s, matches=53758, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  33%|███▎      | 60550/184988 [20:49<46:47, 44.32it/s, matches=54169, match_rate=89.5%]

Error parsing coordinate '21*20'': object of type 'int' has no len()
Error parsing coordinate '21*20'': object of type 'int' has no len()

Processing accidents:  33%|███▎      | 60600/184988 [20:50<44:40, 46.41it/s, matches=54215, match_rate=89.5%]

Error parsing coordinate '21*42'': object of type 'int' has no len()
Error parsing coordinate '21*42'': object of type 'int' has no len()

Processing accidents:  33%|███▎      | 60750/184988 [20:54<43:43, 47.35it/s, matches=54352, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  33%|███▎      | 60950/184988 [20:57<41:14, 50.13it/s, matches=54530, match_rate=89.5%]

Error parsing coordinate '21*37'': object of type 'int' has no len()
Error parsing coordinate '21*37'': object of type 'int' has no len()

Processing accidents:  33%|███▎      | 61000/184988 [20:59<42:39, 48.45it/s, matches=54577, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  33%|███▎      | 61100/184988 [21:01<45:11, 45.69it/s, matches=54670, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  33%|███▎      | 61150/184988 [21:02<45:00, 45.85it/s, matches=54718, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  33%|███▎      | 61200/184988 [21:03<43:11, 47.77it/s, matches=54763, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  33%|███▎      | 61350/184988 [21:06<41:17, 49.91it/s, matches=54898, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  33%|███▎      | 61400/184988 [21:07<41:22, 49.78it/s, matches=54945, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  33%|███▎      | 61500/184988 [21:09<41:32, 49.53it/s, matches=55038, match_rate=89.5%]

Error parsing coordinate '21*14'': object of type 'int' has no len()
Error parsing coordinate '21*14'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  33%|███▎      | 61550/184988 [21:10<41:09, 49.98it/s, matches=55080, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  33%|███▎      | 61600/184988 [21:11<40:19, 51.00it/s, matches=55124, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  33%|███▎      | 61750/184988 [21:14<40:13, 51.07it/s, matches=55262, match_rate=89.5%]

Error parsing coordinate '21*38'': object of type 'int' has no len()
Error parsing coordinate '21*38'': object of type 'int' has no len()

Processing accidents:  33%|███▎      | 61850/184988 [21:16<42:55, 47.82it/s, matches=55351, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  34%|███▎      | 62200/184988 [21:23<41:20, 49.50it/s, matches=55670, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  34%|███▍      | 62500/184988 [21:30<43:12, 47.25it/s, matches=55947, match_rate=89.5%]

Error parsing coordinate '21*29'': object of type 'int' has no len()
Error parsing coordinate '21*29'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  34%|███▍      | 62900/184988 [21:38<44:03, 46.19it/s, matches=56315, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  34%|███▍      | 63350/184988 [21:48<47:00, 43.13it/s, matches=56727, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  34%|███▍      | 63500/184988 [21:51<44:37, 45.37it/s, matches=56871, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  34%|███▍      | 63550/184988 [21:52<44:26, 45.55it/s, matches=56914, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  35%|███▍      | 64100/184988 [22:04<45:28, 44.31it/s, matches=57420, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  35%|███▍      | 64400/184988 [22:11<44:44, 44.93it/s, matches=57691, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  35%|███▍      | 64450/184988 [22:12<43:39, 46.02it/s, matches=57733, match_rate=89.6%]

Error parsing coordinate '21*21'': object of type 'int' has no len()
Error parsing coordinate '21*21'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  35%|███▍      | 64550/184988 [22:14<42:24, 47.33it/s, matches=57825, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  35%|███▍      | 64650/184988 [22:16<41:52, 47.89it/s, matches=57911, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  35%|███▌      | 64950/184988 [22:22<36:12, 55.24it/s, matches=58187, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)

Error parsing coordinate '21*18'': object of type 'int' has no len()
Error parsing coordinate '21*18'': object of type 'int' has no len()

Processing accidents:  35%|███▌      | 65100/184988 [22:24<35:24, 56.42it/s, matches=58323, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  35%|███▌      | 65200/184988 [22:26<34:32, 57.81it/s, matches=58414, match_rate=89.6%]

Error parsing coordinate '52*14'3'1': could not convert string to float: "3'1"
Error parsing coordinate '52*14'3'1': could not convert string to float: "3'1"

Processing accidents:  35%|███▌      | 65600/184988 [22:33<34:30, 57.65it/s, matches=58785, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  35%|███▌      | 65650/184988 [22:34<33:46, 58.89it/s, matches=58828, match_rate=89.6%]

Error parsing coordinate '20*99'': object of type 'int' has no len()
Error parsing coordinate '20*99'': object of type 'int' has no len()

Processing accidents:  36%|███▌      | 65750/184988 [22:36<34:28, 57.65it/s, matches=58921, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  36%|███▌      | 66050/184988 [22:41<34:29, 57.47it/s, matches=59186, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  36%|███▌      | 66350/184988 [22:46<35:23, 55.87it/s, matches=59454, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  36%|███▌      | 66600/184988 [22:51<35:02, 56.32it/s, matches=59677, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  36%|███▋      | 67100/184988 [22:59<33:27, 58.72it/s, matches=60142, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  36%|███▋      | 67400/184988 [23:04<33:13, 58.98it/s, matches=60413, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  36%|███▋      | 67450/184988 [23:05<33:54, 57.78it/s, matches=60459, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  37%|███▋      | 67550/184988 [23:07<33:48, 57.88it/s, matches=60547, match_rate=89.6%]

Error parsing coordinate '21*14'': object of type 'int' has no len()
Error parsing coordinate '21*14'': object of type 'int' has no len()

Processing accidents:  37%|███▋      | 67700/184988 [23:10<33:39, 58.08it/s, matches=60688, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  37%|███▋      | 67750/184988 [23:10<32:36, 59.92it/s, matches=60733, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  37%|███▋      | 67950/184988 [23:14<35:29, 54.96it/s, matches=60916, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  37%|███▋      | 68100/184988 [23:17<35:54, 54.25it/s, matches=61053, match_rate=89.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  37%|███▋      | 68250/184988 [23:20<34:25, 56.53it/s, matches=61189, match_rate=89.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  37%|███▋      | 68300/184988 [23:20<34:24, 56.51it/s, matches=61234, match_rate=89.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  37%|███▋      | 68350/184988 [23:21<34:01, 57.14it/s, matches=61278, match_rate=89.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  37%|███▋      | 68600/184988 [23:26<40:13, 48.23it/s, matches=61507, match_rate=89.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  37%|███▋      | 68900/184988 [23:32<34:22, 56.30it/s, matches=61785, match_rate=89.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  37%|███▋      | 69200/184988 [23:37<34:23, 56.12it/s, matches=62052, match_rate=89.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  37%|███▋      | 69350/184988 [23:40<33:56, 56.77it/s, matches=62192, match_rate=89.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  38%|███▊      | 69400/184988 [23:41<34:40, 55.55it/s, matches=62240, match_rate=89.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  38%|███▊      | 69550/184988 [23:44<34:04, 56.46it/s, matches=62381, match_rate=89.7%]

Error parsing coordinate '21*40'': object of type 'int' has no len()
Error parsing coordinate '21*40'': object of type 'int' has no len()

Processing accidents:  38%|███▊      | 69750/184988 [23:47<33:51, 56.72it/s, matches=62568, match_rate=89.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  38%|███▊      | 69950/184988 [23:51<34:31, 55.54it/s, matches=62753, match_rate=89.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  38%|███▊      | 70100/184988 [23:53<33:17, 57.51it/s, matches=62889, match_rate=89.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  38%|███▊      | 70150/184988 [23:54<34:36, 55.29it/s, matches=62937, match_rate=89.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  38%|███▊      | 70450/184988 [24:00<33:25, 57.11it/s, matches=63209, match_rate=89.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  38%|███▊      | 70750/184988 [24:05<32:01, 59.45it/s, matches=63484, match_rate=89.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  38%|███▊      | 71000/184988 [24:09<32:20, 58.73it/s, matches=63716, match_rate=89.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  39%|███▊      | 71250/184988 [24:14<33:45, 56.15it/s, matches=63952, match_rate=89.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  39%|███▊      | 71500/184988 [24:18<33:33, 56.37it/s, matches=64186, match_rate=89.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  39%|███▊      | 71550/184988 [24:19<33:50, 55.88it/s, matches=64227, match_rate=89.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  39%|███▉      | 71900/184988 [24:25<33:01, 57.08it/s, matches=64558, match_rate=89.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  39%|███▉      | 72000/184988 [24:27<33:09, 56.78it/s, matches=64651, match_rate=89.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  39%|███▉      | 72600/184988 [24:37<32:10, 58.23it/s, matches=65200, match_rate=89.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  39%|███▉      | 72850/184988 [24:41<31:19, 59.65it/s, matches=65426, match_rate=89.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  40%|███▉      | 73100/184988 [24:45<31:20, 59.50it/s, matches=65654, match_rate=89.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  40%|███▉      | 73750/184988 [24:56<31:12, 59.41it/s, matches=66247, match_rate=89.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  40%|███▉      | 73850/184988 [24:58<30:33, 60.63it/s, matches=66341, match_rate=89.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  40%|████      | 74100/184988 [25:02<32:20, 57.14it/s, matches=66572, match_rate=89.8%]

Error parsing coordinate '21*17'': object of type 'int' has no len()
Error parsing coordinate '21*17'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  40%|████      | 74700/184988 [25:13<31:19, 58.68it/s, matches=67127, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  40%|████      | 74750/184988 [25:13<30:38, 59.95it/s, matches=67171, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  40%|████      | 74850/184988 [25:15<30:33, 60.08it/s, matches=67259, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  41%|████      | 75000/184988 [25:18<32:18, 56.74it/s, matches=67394, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  41%|████      | 75200/184988 [25:21<30:19, 60.34it/s, matches=67578, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  41%|████      | 75300/184988 [25:23<32:11, 56.80it/s, matches=67669, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  41%|████      | 75350/184988 [25:24<31:37, 57.79it/s, matches=67715, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  41%|████      | 75500/184988 [25:26<30:55, 59.01it/s, matches=67855, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  41%|████      | 75600/184988 [25:28<31:44, 57.44it/s, matches=67945, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  41%|████      | 75700/184988 [25:30<32:25, 56.17it/s, matches=68033, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  41%|████      | 75750/184988 [25:31<31:58, 56.95it/s, matches=68074, match_rate=89.9%]

Error parsing coordinate '52*19'H': could not convert string to float: 'H'
Error parsing coordinate '52*19'H': could not convert string to float: 'H'

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  41%|████      | 75800/184988 [25:32<31:43, 57.36it/s, matches=68119, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  41%|████      | 75850/184988 [25:32<30:48, 59.05it/s, matches=68163, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  41%|████      | 75900/184988 [25:33<30:13, 60.14it/s, matches=68210, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  41%|████      | 76000/184988 [25:35<30:46, 59.02it/s, matches=68302, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  41%|████      | 76300/184988 [25:40<30:07, 60.14it/s, matches=68571, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  42%|████▏     | 76900/184988 [25:51<32:13, 55.89it/s, matches=69118, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  42%|████▏     | 77400/184988 [25:59<31:03, 57.73it/s, matches=69571, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  42%|████▏     | 78000/184988 [26:09<29:21, 60.75it/s, matches=70107, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  42%|████▏     | 78100/184988 [26:11<31:58, 55.70it/s, matches=70197, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  43%|████▎     | 79200/184988 [26:30<29:25, 59.92it/s, matches=71219, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  43%|████▎     | 79350/184988 [26:33<29:41, 59.30it/s, matches=71356, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  43%|████▎     | 79550/184988 [26:36<30:57, 56.77it/s, matches=71541, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  43%|████▎     | 79650/184988 [26:38<30:33, 57.45it/s, matches=71630, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  43%|████▎     | 80200/184988 [26:48<32:39, 53.48it/s, matches=72137, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  43%|████▎     | 80400/184988 [26:51<31:18, 55.68it/s, matches=72320, match_rate=90.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  43%|████▎     | 80450/184988 [26:52<33:16, 52.37it/s, matches=72364, match_rate=89.9%]

Error parsing coordinate '21*09'': object of type 'int' has no len()
Error parsing coordinate '21*09'': object of type 'int' has no len()

Processing accidents:  44%|████▎     | 80650/184988 [26:56<30:58, 56.15it/s, matches=72549, match_rate=90.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  44%|████▎     | 80750/184988 [26:58<30:11, 57.53it/s, matches=72641, match_rate=90.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  44%|████▎     | 80850/184988 [26:59<30:11, 57.50it/s, matches=72731, match_rate=90.0%]

Error parsing coordinate '21*20'': object of type 'int' has no len()
Error parsing coordinate '21*20'': object of type 'int' has no len()

Processing accidents:  44%|████▍     | 80950/184988 [27:01<31:01, 55.90it/s, matches=72825, match_rate=90.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  44%|████▍     | 81100/184988 [27:04<31:08, 55.60it/s, matches=72963, match_rate=90.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  44%|████▍     | 81150/184988 [27:05<31:35, 54.78it/s, matches=73006, match_rate=90.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  44%|████▍     | 81350/184988 [27:08<29:17, 58.97it/s, matches=73191, match_rate=90.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  44%|████▍     | 81950/184988 [27:19<30:16, 56.74it/s, matches=73710, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  44%|████▍     | 82050/184988 [27:20<29:56, 57.31it/s, matches=73793, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  45%|████▍     | 82450/184988 [27:27<29:20, 58.25it/s, matches=74149, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  45%|████▍     | 83000/184988 [27:41<39:53, 42.61it/s, matches=74624, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  45%|████▍     | 83200/184988 [27:44<32:15, 52.59it/s, matches=74802, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  45%|████▌     | 83450/184988 [27:49<30:52, 54.82it/s, matches=75023, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  45%|████▌     | 83550/184988 [27:51<30:52, 54.75it/s, matches=75108, match_rate=89.9%]

Error parsing coordinate '21*21'': object of type 'int' has no len()
Error parsing coordinate '21*21'': object of type 'int' has no len()

Processing accidents:  45%|████▌     | 83700/184988 [27:53<29:57, 56.34it/s, matches=75242, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  46%|████▌     | 84450/184988 [28:07<32:07, 52.17it/s, matches=75909, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  46%|████▌     | 85000/184988 [28:17<30:02, 55.48it/s, matches=76377, match_rate=89.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  46%|████▌     | 85300/184988 [28:22<28:34, 58.13it/s, matches=76637, match_rate=89.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  46%|████▌     | 85450/184988 [28:25<30:17, 54.76it/s, matches=76765, match_rate=89.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  46%|████▌     | 85550/184988 [28:27<30:22, 54.56it/s, matches=76848, match_rate=89.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  47%|████▋     | 86300/184988 [28:40<29:54, 55.01it/s, matches=77511, match_rate=89.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  47%|████▋     | 86450/184988 [28:43<29:44, 55.22it/s, matches=77648, match_rate=89.8%]

Error parsing coordinate '21*61'': object of type 'int' has no len()
Error parsing coordinate '21*61'': object of type 'int' has no len()

Processing accidents:  47%|████▋     | 86650/184988 [28:47<29:43, 55.14it/s, matches=77828, match_rate=89.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  47%|████▋     | 86850/184988 [28:50<29:12, 56.01it/s, matches=77995, match_rate=89.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  47%|████▋     | 87450/184988 [29:01<28:37, 56.79it/s, matches=78525, match_rate=89.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  48%|████▊     | 87950/184988 [29:10<29:25, 54.95it/s, matches=78973, match_rate=89.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  48%|████▊     | 88250/184988 [29:16<28:46, 56.02it/s, matches=79234, match_rate=89.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  48%|████▊     | 88450/184988 [29:19<28:16, 56.90it/s, matches=79403, match_rate=89.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  48%|████▊     | 88700/184988 [29:23<27:55, 57.45it/s, matches=79616, match_rate=89.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  49%|████▉     | 91250/184988 [30:14<27:14, 57.33it/s, matches=81819, match_rate=89.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  49%|████▉     | 91300/184988 [30:15<27:33, 56.68it/s, matches=81861, match_rate=89.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  50%|█████     | 92550/184988 [30:45<42:02, 36.65it/s, matches=82926, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  50%|█████     | 93200/184988 [31:00<32:30, 47.06it/s, matches=83495, match_rate=89.6%]

Error parsing coordinate '21*51'': object of type 'int' has no len()
Error parsing coordinate '21*51'': object of type 'int' has no len()

Processing accidents:  51%|█████     | 93600/184988 [31:08<32:04, 47.50it/s, matches=83841, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  51%|█████     | 93650/184988 [31:09<32:30, 46.83it/s, matches=83884, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  51%|█████     | 94100/184988 [31:18<30:26, 49.77it/s, matches=84273, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  51%|█████     | 94250/184988 [31:21<28:46, 52.57it/s, matches=84404, match_rate=89.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  51%|█████▏    | 95050/184988 [31:36<27:19, 54.85it/s, matches=85109, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  51%|█████▏    | 95250/184988 [31:39<27:55, 53.55it/s, matches=85276, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  52%|█████▏    | 95400/184988 [31:42<26:29, 56.36it/s, matches=85404, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  52%|█████▏    | 95500/184988 [31:44<26:35, 56.10it/s, matches=85486, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  52%|█████▏    | 95650/184988 [31:46<26:03, 57.15it/s, matches=85617, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  52%|█████▏    | 95750/184988 [31:48<24:56, 59.61it/s, matches=85701, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  52%|█████▏    | 95800/184988 [31:49<25:03, 59.34it/s, matches=85745, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  52%|█████▏    | 95900/184988 [31:50<25:51, 57.41it/s, matches=85834, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  52%|█████▏    | 96300/184988 [31:58<27:16, 54.19it/s, matches=86193, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  52%|█████▏    | 96500/184988 [32:01<25:42, 57.35it/s, matches=86372, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  52%|█████▏    | 96600/184988 [32:03<25:18, 58.21it/s, matches=86463, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  52%|█████▏    | 96650/184988 [32:04<24:29, 60.10it/s, matches=86509, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  52%|█████▏    | 96800/184988 [32:06<25:56, 56.66it/s, matches=86629, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  52%|█████▏    | 96850/184988 [32:07<25:54, 56.70it/s, matches=86671, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  52%|█████▏    | 96900/184988 [32:08<25:51, 56.79it/s, matches=86713, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  52%|█████▏    | 96950/184988 [32:09<25:57, 56.53it/s, matches=86756, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  52%|█████▏    | 97000/184988 [32:10<25:21, 57.81it/s, matches=86798, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  52%|█████▏    | 97050/184988 [32:11<24:52, 58.91it/s, matches=86839, match_rate=89.5%]

Error parsing coordinate '21*24'': object of type 'int' has no len()
Error parsing coordinate '21*24'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  52%|█████▏    | 97100/184988 [32:12<25:18, 57.86it/s, matches=86879, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  53%|█████▎    | 97150/184988 [32:12<25:23, 57.67it/s, matches=86919, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  53%|█████▎    | 97250/184988 [32:14<24:51, 58.84it/s, matches=87004, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  53%|█████▎    | 97350/184988 [32:16<26:00, 56.18it/s, matches=87087, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  53%|█████▎    | 97450/184988 [32:18<25:38, 56.89it/s, matches=87173, match_rate=89.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  53%|█████▎    | 97600/184988 [32:20<26:20, 55.31it/s, matches=87302, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  53%|█████▎    | 97900/184988 [32:26<26:31, 54.73it/s, matches=87571, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  53%|█████▎    | 97950/184988 [32:27<25:26, 57.01it/s, matches=87614, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  53%|█████▎    | 98000/184988 [32:28<25:07, 57.72it/s, matches=87658, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  53%|█████▎    | 98050/184988 [32:29<25:48, 56.13it/s, matches=87702, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  53%|█████▎    | 98100/184988 [32:29<25:34, 56.61it/s, matches=87747, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  53%|█████▎    | 98150/184988 [32:30<25:53, 55.88it/s, matches=87790, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  53%|█████▎    | 98250/184988 [32:32<25:34, 56.52it/s, matches=87874, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  53%|█████▎    | 98400/184988 [32:35<26:07, 55.23it/s, matches=87997, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  53%|█████▎    | 98600/184988 [32:38<25:14, 57.04it/s, matches=88163, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  53%|█████▎    | 98700/184988 [32:40<24:58, 57.57it/s, matches=88246, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  53%|█████▎    | 98750/184988 [32:41<26:00, 55.28it/s, matches=88288, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  53%|█████▎    | 98850/184988 [32:43<24:52, 57.72it/s, matches=88371, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  53%|█████▎    | 98900/184988 [32:44<25:13, 56.88it/s, matches=88416, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  53%|█████▎    | 98950/184988 [32:44<24:59, 57.39it/s, matches=88459, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  54%|█████▎    | 99000/184988 [32:45<25:19, 56.58it/s, matches=88502, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  54%|█████▎    | 99050/184988 [32:46<25:13, 56.80it/s, matches=88549, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  54%|█████▎    | 99100/184988 [32:47<24:37, 58.12it/s, matches=88594, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  54%|█████▎    | 99150/184988 [32:48<24:15, 58.99it/s, matches=88634, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  54%|█████▎    | 99200/184988 [32:49<25:29, 56.08it/s, matches=88679, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  54%|█████▎    | 99300/184988 [32:51<25:24, 56.22it/s, matches=88764, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  54%|█████▍    | 99550/184988 [32:55<25:00, 56.92it/s, matches=88968, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  54%|█████▍    | 99600/184988 [32:56<25:20, 56.17it/s, matches=89010, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  54%|█████▍    | 99650/184988 [32:57<25:08, 56.59it/s, matches=89054, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  54%|█████▍    | 99700/184988 [32:58<25:05, 56.65it/s, matches=89090, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  54%|█████▍    | 99850/184988 [33:00<26:37, 53.28it/s, matches=89217, match_rate=89.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  54%|█████▍    | 99950/184988 [33:02<25:37, 55.32it/s, matches=89305, match_rate=89.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  54%|█████▍    | 100200/184988 [33:07<24:43, 57.14it/s, matches=89516, match_rate=89.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  54%|█████▍    | 100350/184988 [33:09<24:29, 57.59it/s, matches=89642, match_rate=89.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  54%|█████▍    | 100450/184988 [33:11<25:33, 55.14it/s, matches=89729, match_rate=89.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  54%|█████▍    | 100500/184988 [33:12<25:38, 54.90it/s, matches=89771, match_rate=89.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  54%|█████▍    | 100550/184988 [33:13<25:48, 54.51it/s, matches=89817, match_rate=89.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)

Error parsing coordinate '21*04'': object of type 'int' has no len()
Error parsing coordinate '21*04'': object of type 'int' has no len()

Processing accidents:  55%|█████▌    | 102350/184988 [33:45<23:19, 59.06it/s, matches=91328, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  55%|█████▌    | 102550/184988 [33:48<23:28, 58.54it/s, matches=91503, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  55%|█████▌    | 102600/184988 [33:49<25:10, 54.55it/s, matches=91547, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  55%|█████▌    | 102650/184988 [33:50<25:00, 54.86it/s, matches=91593, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  56%|█████▌    | 102700/184988 [33:51<24:35, 55.76it/s, matches=91637, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  56%|█████▌    | 102800/184988 [33:53<23:29, 58.32it/s, matches=91719, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  56%|█████▌    | 102900/184988 [33:54<23:18, 58.70it/s, matches=91801, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  56%|█████▌    | 102950/184988 [33:55<23:50, 57.34it/s, matches=91843, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  56%|█████▌    | 103100/184988 [33:58<23:59, 56.89it/s, matches=91970, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  56%|█████▌    | 103150/184988 [33:59<23:34, 57.85it/s, matches=92012, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  56%|█████▌    | 103300/184988 [34:01<22:59, 59.24it/s, matches=92141, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  56%|█████▌    | 103350/184988 [34:02<23:06, 58.88it/s, matches=92178, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  56%|█████▌    | 103400/184988 [34:03<23:36, 57.60it/s, matches=92220, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  56%|█████▌    | 103450/184988 [34:04<23:33, 57.67it/s, matches=92264, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  56%|█████▌    | 103500/184988 [34:05<24:14, 56.02it/s, matches=92306, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  56%|█████▌    | 103550/184988 [34:06<23:57, 56.66it/s, matches=92347, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  56%|█████▌    | 103700/184988 [34:09<25:16, 53.60it/s, matches=92477, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)

Error parsing coordinate '21*29'': object of type 'int' has no len()
Error parsing coordinate '21*29'': object of type 'int' has no len()

Processing accidents:  56%|█████▌    | 103800/184988 [34:10<24:47, 54.58it/s, matches=92556, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  56%|█████▌    | 103900/184988 [34:12<24:54, 54.27it/s, matches=92644, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)

Error parsing coordinate '21*18'': object of type 'int' has no len()
Error parsing coordinate '21*18'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  56%|█████▌    | 104000/184988 [34:14<25:04, 53.83it/s, matches=92728, match_rate=89.2%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  56%|█████▋    | 104100/184988 [34:16<24:26, 55.16it/s, matches=92803, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)

Error parsing coordinate '21*17'': object of type 'int' has no len()
Error parsing coordinate '21*17'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  56%|█████▋    | 104150/184988 [34:17<24:36, 54.75it/s, matches=92842, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  56%|█████▋    | 104200/184988 [34:18<24:21, 55.27it/s, matches=92883, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  56%|█████▋    | 104350/184988 [34:20<23:33, 57.04it/s, matches=93008, match_rate=89.1%]

Error parsing coordinate '21*44'': object of type 'int' has no len()
Error parsing coordinate '21*44'': object of type 'int' has no len()

Processing accidents:  56%|█████▋    | 104400/184988 [34:21<23:47, 56.45it/s, matches=93050, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  57%|█████▋    | 104600/184988 [34:25<24:06, 55.56it/s, matches=93225, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  57%|█████▋    | 104650/184988 [34:26<24:05, 55.59it/s, matches=93268, match_rate=89.1%]

Error parsing coordinate '21*04'': object of type 'int' has no len()
Error parsing coordinate '21*04'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  57%|█████▋    | 104750/184988 [34:28<24:01, 55.67it/s, matches=93349, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  57%|█████▋    | 104900/184988 [34:30<25:04, 53.22it/s, matches=93475, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  57%|█████▋    | 104950/184988 [34:31<24:55, 53.53it/s, matches=93520, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  57%|█████▋    | 105000/184988 [34:32<24:39, 54.05it/s, matches=93565, match_rate=89.1%]

Error parsing coordinate '52*21'': object of type 'int' has no len()
Error parsing coordinate '20*98'': object of type 'int' has no len()
Error parsing coordinate '52*21'': object of type 'int' has no len()
Error parsing coordinate '20*98'': object of type 'int' has no len()

Processing accidents:  57%|█████▋    | 105050/184988 [34:33<24:38, 54.07it/s, matches=93607, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  57%|█████▋    | 105200/184988 [34:36<23:26, 56.73it/s, matches=93735, match_rate=89.1%]

Error parsing coordinate '21*11'': object of type 'int' has no len()
Error parsing coordinate '21*11'': object of type 'int' has no len()

Processing accidents:  57%|█████▋    | 105300/184988 [34:38<23:17, 57.02it/s, matches=93816, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  57%|█████▋    | 105350/184988 [34:38<23:41, 56.03it/s, matches=93857, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  57%|█████▋    | 105450/184988 [34:40<24:05, 55.03it/s, matches=93942, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  57%|█████▋    | 105550/184988 [34:42<23:21, 56.69it/s, matches=94027, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  57%|█████▋    | 105600/184988 [34:43<23:49, 55.53it/s, matches=94069, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  57%|█████▋    | 105750/184988 [34:46<24:08, 54.69it/s, matches=94200, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  57%|█████▋    | 105850/184988 [34:48<24:09, 54.60it/s, matches=94294, match_rate=89.1%]

Error parsing coordinate '52*13'': object of type 'int' has no len()
Error parsing coordinate '20*59'': object of type 'int' has no len()
Error parsing coordinate '52*13'': object of type 'int' has no len()
Error parsing coordinate '20*59'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  57%|█████▋    | 105900/184988 [34:48<23:30, 56.09it/s, matches=94332, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  57%|█████▋    | 105950/184988 [34:49<23:31, 55.99it/s, matches=94374, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  57%|█████▋    | 106100/184988 [34:52<24:38, 53.37it/s, matches=94499, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  57%|█████▋    | 106200/184988 [34:54<24:08, 54.40it/s, matches=94586, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  58%|█████▊    | 106400/184988 [34:58<23:51, 54.92it/s, matches=94754, match_rate=89.1%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  58%|█████▊    | 106600/184988 [35:01<23:11, 56.33it/s, matches=94921, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  58%|█████▊    | 106750/184988 [35:04<23:23, 55.74it/s, matches=95049, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  58%|█████▊    | 106800/184988 [35:05<23:06, 56.39it/s, matches=95094, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  58%|█████▊    | 106900/184988 [35:07<23:50, 54.60it/s, matches=95181, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  58%|█████▊    | 106950/184988 [35:08<24:29, 53.10it/s, matches=95220, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  58%|█████▊    | 107000/184988 [35:08<23:29, 55.34it/s, matches=95263, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  58%|█████▊    | 107100/184988 [35:10<22:57, 56.55it/s, matches=95347, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  58%|█████▊    | 107200/184988 [35:12<22:02, 58.81it/s, matches=95427, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  58%|█████▊    | 107300/184988 [35:14<22:54, 56.51it/s, matches=95509, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  58%|█████▊    | 107450/184988 [35:16<22:57, 56.27it/s, matches=95643, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  58%|█████▊    | 107650/184988 [35:20<22:41, 56.81it/s, matches=95819, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  58%|█████▊    | 107700/184988 [35:21<23:29, 54.83it/s, matches=95862, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  58%|█████▊    | 107750/184988 [35:22<23:17, 55.26it/s, matches=95906, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  58%|█████▊    | 107850/184988 [35:23<23:09, 55.50it/s, matches=95991, match_rate=89.0%]

Error parsing coordinate '21*22'': object of type 'int' has no len()
Error parsing coordinate '21*22'': object of type 'int' has no len()

Processing accidents:  58%|█████▊    | 107900/184988 [35:24<22:51, 56.21it/s, matches=96034, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  58%|█████▊    | 108000/184988 [35:26<23:47, 53.92it/s, matches=96121, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  58%|█████▊    | 108050/184988 [35:27<23:13, 55.21it/s, matches=96162, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  59%|█████▊    | 108400/184988 [35:33<21:43, 58.75it/s, matches=96459, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  59%|█████▊    | 108600/184988 [35:37<22:43, 56.04it/s, matches=96629, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  59%|█████▉    | 108700/184988 [35:38<22:03, 57.62it/s, matches=96717, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  59%|█████▉    | 108800/184988 [35:40<22:29, 56.45it/s, matches=96802, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  59%|█████▉    | 108850/184988 [35:41<22:00, 57.68it/s, matches=96842, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  59%|█████▉    | 108900/184988 [35:42<22:41, 55.87it/s, matches=96889, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  59%|█████▉    | 108950/184988 [35:43<22:49, 55.54it/s, matches=96933, match_rate=89.0%]

Error parsing coordinate '52*12'': object of type 'int' has no len()
Error parsing coordinate '20*56'': object of type 'int' has no len()
Error parsing coordinate '52*12'': object of type 'int' has no len()
Error parsing coordinate '20*56'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  59%|█████▉    | 109000/184988 [35:44<22:10, 57.10it/s, matches=96972, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  59%|█████▉    | 109050/184988 [35:45<22:22, 56.57it/s, matches=97010, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  59%|█████▉    | 109100/184988 [35:45<22:09, 57.06it/s, matches=97054, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  59%|█████▉    | 109150/184988 [35:46<22:14, 56.81it/s, matches=97092, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  59%|█████▉    | 109200/184988 [35:47<21:48, 57.90it/s, matches=97135, match_rate=89.0%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  59%|█████▉    | 109250/184988 [35:48<21:44, 58.04it/s, matches=97177, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  59%|█████▉    | 109400/184988 [35:51<21:40, 58.11it/s, matches=97300, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  59%|█████▉    | 109450/184988 [35:51<21:37, 58.21it/s, matches=97343, match_rate=88.9%]

Error parsing coordinate '21*38'': object of type 'int' has no len()
Error parsing coordinate '21*38'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  59%|█████▉    | 109500/184988 [35:52<22:03, 57.02it/s, matches=97383, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  59%|█████▉    | 109600/184988 [35:54<22:00, 57.11it/s, matches=97467, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  59%|█████▉    | 109750/184988 [35:57<22:07, 56.69it/s, matches=97595, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  59%|█████▉    | 109800/184988 [35:58<23:11, 54.03it/s, matches=97637, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  59%|█████▉    | 109950/184988 [36:00<21:46, 57.41it/s, matches=97766, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  59%|█████▉    | 110050/184988 [36:02<23:05, 54.07it/s, matches=97852, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  60%|█████▉    | 110100/184988 [36:03<23:07, 53.98it/s, matches=97893, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  60%|█████▉    | 110150/184988 [36:04<23:04, 54.07it/s, matches=97939, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  60%|█████▉    | 110200/184988 [36:05<22:59, 54.20it/s, matches=97980, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  60%|█████▉    | 110300/184988 [36:07<23:06, 53.87it/s, matches=98061, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  60%|█████▉    | 110350/184988 [36:08<22:31, 55.24it/s, matches=98102, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  60%|█████▉    | 110450/184988 [36:10<22:06, 56.18it/s, matches=98189, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  60%|█████▉    | 110500/184988 [36:10<22:01, 56.37it/s, matches=98231, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  60%|█████▉    | 110600/184988 [36:12<22:16, 55.67it/s, matches=98318, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  60%|█████▉    | 110700/184988 [36:14<22:02, 56.18it/s, matches=98402, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  60%|█████▉    | 110750/184988 [36:15<21:51, 56.60it/s, matches=98442, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  60%|█████▉    | 110800/184988 [36:16<22:09, 55.81it/s, matches=98483, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  60%|█████▉    | 110900/184988 [36:18<22:06, 55.86it/s, matches=98568, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  60%|██████    | 111000/184988 [36:19<21:35, 57.13it/s, matches=98648, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  60%|██████    | 111050/184988 [36:20<21:41, 56.81it/s, matches=98689, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  60%|██████    | 111150/184988 [36:22<21:16, 57.82it/s, matches=98776, match_rate=88.9%]

Error parsing coordinate '20*95'': object of type 'int' has no len()
Error parsing coordinate '20*95'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  60%|██████    | 111200/184988 [36:23<21:30, 57.17it/s, matches=98821, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  60%|██████    | 111350/184988 [36:26<21:43, 56.48it/s, matches=98951, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  60%|██████    | 111450/184988 [36:27<21:53, 55.99it/s, matches=99035, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  60%|██████    | 111650/184988 [36:31<21:52, 55.87it/s, matches=99208, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  60%|██████    | 111850/184988 [36:34<20:46, 58.69it/s, matches=99385, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  61%|██████    | 111950/184988 [36:36<20:54, 58.23it/s, matches=99471, match_rate=88.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  61%|██████    | 112050/184988 [36:38<20:18, 59.87it/s, matches=99549, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  61%|██████    | 112200/184988 [36:40<21:36, 56.12it/s, matches=99680, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  61%|██████    | 112250/184988 [36:41<21:30, 56.36it/s, matches=99722, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  61%|██████    | 112450/184988 [36:45<21:58, 55.01it/s, matches=99895, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  61%|██████    | 112500/184988 [36:46<21:36, 55.91it/s, matches=99936, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  61%|██████    | 112600/184988 [36:48<21:29, 56.15it/s, matches=1e+5, match_rate=88.8%] C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  61%|██████    | 112700/184988 [36:49<21:02, 57.26it/s, matches=1e+5, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  61%|██████    | 112750/184988 [36:50<20:52, 57.68it/s, matches=1e+5, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  61%|██████    | 112950/184988 [36:54<21:43, 55.24it/s, matches=1e+5, match_rate=88.8%]

Error parsing coordinate '21*36'': object of type 'int' has no len()
Error parsing coordinate '21*36'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  61%|██████    | 113150/184988 [36:57<21:17, 56.21it/s, matches=1e+5, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  61%|██████    | 113200/184988 [36:58<21:16, 56.22it/s, matches=100537, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  61%|██████▏   | 113400/184988 [37:01<20:32, 58.08it/s, matches=100706, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  61%|██████▏   | 113450/184988 [37:02<21:03, 56.64it/s, matches=100747, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  61%|██████▏   | 113500/184988 [37:03<20:47, 57.33it/s, matches=100790, match_rate=88.8%]

Error parsing coordinate '21*03'': object of type 'int' has no len()
Error parsing coordinate '21*03'': object of type 'int' has no len()

Processing accidents:  61%|██████▏   | 113750/184988 [37:08<20:50, 56.99it/s, matches=101008, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  62%|██████▏   | 113850/184988 [37:09<20:33, 57.69it/s, matches=101087, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  62%|██████▏   | 113950/184988 [37:11<20:44, 57.08it/s, matches=101176, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  62%|██████▏   | 114000/184988 [37:12<21:02, 56.23it/s, matches=101218, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  62%|██████▏   | 114200/184988 [37:15<20:08, 58.55it/s, matches=101380, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  62%|██████▏   | 114300/184988 [37:17<20:06, 58.57it/s, matches=101468, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  62%|██████▏   | 114400/184988 [37:19<21:00, 56.01it/s, matches=101552, match_rate=88.8%]

Error parsing coordinate '21*24'': object of type 'int' has no len()
Error parsing coordinate '21*24'': object of type 'int' has no len()

Processing accidents:  62%|██████▏   | 114450/184988 [37:20<20:25, 57.54it/s, matches=101595, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  62%|██████▏   | 114600/184988 [37:22<20:30, 57.22it/s, matches=101721, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  62%|██████▏   | 114700/184988 [37:24<21:06, 55.51it/s, matches=101805, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  62%|██████▏   | 114750/184988 [37:25<20:43, 56.50it/s, matches=101843, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  62%|██████▏   | 114800/184988 [37:26<21:05, 55.48it/s, matches=101885, match_rate=88.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  62%|██████▏   | 114850/184988 [37:27<20:26, 57.19it/s, matches=101923, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  62%|██████▏   | 115050/184988 [37:30<19:54, 58.56it/s, matches=102096, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  62%|██████▏   | 115100/184988 [37:31<20:04, 58.04it/s, matches=102136, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  62%|██████▏   | 115150/184988 [37:32<20:19, 57.25it/s, matches=102181, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  62%|██████▏   | 115250/184988 [37:34<19:52, 58.48it/s, matches=102255, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  62%|██████▏   | 115300/184988 [37:35<19:50, 58.54it/s, matches=102297, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  62%|██████▏   | 115400/184988 [37:36<20:38, 56.18it/s, matches=102374, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  62%|██████▏   | 115450/184988 [37:37<21:13, 54.61it/s, matches=102416, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  62%|██████▏   | 115500/184988 [37:38<21:38, 53.50it/s, matches=102460, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  62%|██████▏   | 115550/184988 [37:39<21:11, 54.60it/s, matches=102499, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  62%|██████▏   | 115600/184988 [37:40<20:59, 55.09it/s, matches=102533, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 115800/184988 [37:44<20:03, 57.48it/s, matches=102709, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 115900/184988 [37:45<20:52, 55.18it/s, matches=102796, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 115950/184988 [37:46<20:32, 56.00it/s, matches=102839, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 116000/184988 [37:47<21:04, 54.55it/s, matches=102882, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 116050/184988 [37:48<20:41, 55.54it/s, matches=102925, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 116150/184988 [37:50<21:14, 54.02it/s, matches=103011, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 116300/184988 [37:53<20:16, 56.45it/s, matches=103145, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 116350/184988 [37:53<19:59, 57.22it/s, matches=103189, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 116400/184988 [37:54<19:48, 57.69it/s, matches=103234, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 116450/184988 [37:55<20:40, 55.26it/s, matches=103277, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 116500/184988 [37:56<20:23, 56.00it/s, matches=103321, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 116550/184988 [37:57<20:30, 55.64it/s, matches=103366, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 116600/184988 [37:58<20:28, 55.67it/s, matches=103409, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 116700/184988 [38:00<21:28, 52.99it/s, matches=103496, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 116800/184988 [38:02<20:47, 54.65it/s, matches=103576, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 116850/184988 [38:03<20:27, 55.50it/s, matches=103618, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 116900/184988 [38:04<20:35, 55.09it/s, matches=103660, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 117050/184988 [38:06<19:41, 57.49it/s, matches=103790, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 117100/184988 [38:07<19:46, 57.23it/s, matches=103835, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 117200/184988 [38:09<19:08, 59.03it/s, matches=103920, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 117250/184988 [38:10<19:16, 58.57it/s, matches=103961, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  63%|██████▎   | 117350/184988 [38:11<19:37, 57.43it/s, matches=104040, match_rate=88.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance

Error parsing coordinate '52*95'': object of type 'int' has no len()
Error parsing coordinate '52*95'': object of type 'int' has no len()

Processing accidents:  64%|██████▎   | 117800/184988 [38:19<19:22, 57.81it/s, matches=104408, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▎   | 117900/184988 [38:21<19:33, 57.16it/s, matches=104492, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▍   | 117950/184988 [38:22<20:21, 54.87it/s, matches=104528, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▍   | 118000/184988 [38:23<19:48, 56.34it/s, matches=104567, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▍   | 118050/184988 [38:24<20:13, 55.16it/s, matches=104607, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▍   | 118100/184988 [38:25<20:07, 55.39it/s, matches=104641, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▍   | 118150/184988 [38:26<19:52, 56.06it/s, matches=104681, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▍   | 118200/184988 [38:26<19:35, 56.80it/s, matches=104722, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▍   | 118250/184988 [38:27<19:26, 57.20it/s, matches=104760, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▍   | 118350/184988 [38:29<19:19, 57.46it/s, matches=104839, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▍   | 118450/184988 [38:31<18:37, 59.52it/s, matches=104918, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▍   | 118500/184988 [38:32<19:13, 57.64it/s, matches=104958, match_rate=88.6%]

Error parsing coordinate '52*25'': object of type 'int' has no len()
Error parsing coordinate '21*00'': object of type 'int' has no len()
Error parsing coordinate '52*25'': object of type 'int' has no len()
Error parsing coordinate '21*00'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▍   | 118550/184988 [38:32<19:15, 57.50it/s, matches=104999, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▍   | 118600/184988 [38:33<19:17, 57.33it/s, matches=105039, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▍   | 118700/184988 [38:35<19:21, 57.09it/s, matches=105125, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▍   | 118750/184988 [38:36<18:53, 58.42it/s, matches=105167, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▍   | 118800/184988 [38:37<19:53, 55.47it/s, matches=105209, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▍   | 118850/184988 [38:38<19:26, 56.72it/s, matches=105252, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▍   | 118900/184988 [38:39<19:11, 57.38it/s, matches=105298, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▍   | 119050/184988 [38:41<19:12, 57.20it/s, matches=105434, match_rate=88.6%]

Error parsing coordinate '21*05'': object of type 'int' has no len()
Error parsing coordinate '21*05'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▍   | 119150/184988 [38:43<19:18, 56.82it/s, matches=105519, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▍   | 119250/184988 [38:45<19:09, 57.19it/s, matches=105604, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  64%|██████▍   | 119300/184988 [38:46<18:44, 58.43it/s, matches=105645, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▍   | 119350/184988 [38:46<19:05, 57.32it/s, matches=105690, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▍   | 119400/184988 [38:47<18:57, 57.68it/s, matches=105732, match_rate=88.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▍   | 119450/184988 [38:48<18:40, 58.49it/s, matches=105772, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▍   | 119500/184988 [38:49<18:36, 58.67it/s, matches=105809, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)

Error parsing coordinate '52*17'': object of type 'int' has no len()
Error parsing coordinate '21*07'': object of type 'int' has no len()
Error parsing coordinate '52*17'': object of type 'int' has no len()
Error parsing coordinate '21*07'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▍   | 119600/184988 [38:51<18:14, 59.73it/s, matches=105894, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▍   | 119650/184988 [38:51<18:06, 60.15it/s, matches=105939, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▍   | 119700/184988 [38:52<18:55, 57.51it/s, matches=105983, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▍   | 119750/184988 [38:53<18:31, 58.70it/s, matches=106024, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▍   | 119800/184988 [38:54<18:29, 58.74it/s, matches=106066, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▍   | 119850/184988 [38:55<18:35, 58.40it/s, matches=106109, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▍   | 119950/184988 [38:57<19:01, 56.98it/s, matches=106190, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▍   | 120000/184988 [38:58<18:46, 57.67it/s, matches=106231, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▍   | 120050/184988 [38:58<18:31, 58.45it/s, matches=106267, match_rate=88.5%]

Error parsing coordinate '52*22'': object of type 'int' has no len()
Error parsing coordinate '21*00'': object of type 'int' has no len()
Error parsing coordinate '52*22'': object of type 'int' has no len()
Error parsing coordinate '21*00'': object of type 'int' has no len()
Error parsing coordinate '52*18'': object of type 'int' has no len()
Error parsing coordinate '21*01'': object of type 'int' has no len()
Error parsing coordinate '52*18'': object of type 'int' has no len()
Error parsing coordinate '21*01'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▍   | 120100/184988 [38:59<18:02, 59.94it/s, matches=106309, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▍   | 120150/184988 [39:00<18:20, 58.92it/s, matches=106349, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▍   | 120200/184988 [39:01<18:53, 57.17it/s, matches=106392, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▌   | 120250/184988 [39:02<19:00, 56.78it/s, matches=106430, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▌   | 120350/184988 [39:04<19:45, 54.54it/s, matches=106515, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▌   | 120400/184988 [39:05<19:30, 55.19it/s, matches=106560, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▌   | 120500/184988 [39:06<19:19, 55.63it/s, matches=106643, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▌   | 120550/184988 [39:07<18:51, 56.95it/s, matches=106681, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▌   | 120600/184988 [39:08<18:31, 57.92it/s, matches=106725, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▌   | 120650/184988 [39:09<18:46, 57.12it/s, matches=106767, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▌   | 120750/184988 [39:11<18:49, 56.88it/s, matches=106850, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▌   | 120850/184988 [39:13<18:31, 57.73it/s, matches=106937, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▌   | 121000/184988 [39:15<18:30, 57.61it/s, matches=107067, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  65%|██████▌   | 121100/184988 [39:17<20:07, 52.90it/s, matches=107155, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  66%|██████▌   | 121200/184988 [39:19<18:33, 57.28it/s, matches=107241, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  66%|██████▌   | 121250/184988 [39:20<17:44, 59.88it/s, matches=107284, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  66%|██████▌   | 121300/184988 [39:20<18:13, 58.24it/s, matches=107326, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  66%|██████▌   | 121400/184988 [39:22<18:26, 57.48it/s, matches=107419, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  66%|██████▌   | 121500/184988 [39:24<18:25, 57.45it/s, matches=107499, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  66%|██████▌   | 121600/184988 [39:26<17:49, 59.29it/s, matches=107582, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  66%|██████▌   | 121800/184988 [39:29<18:10, 57.94it/s, matches=107751, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  66%|██████▌   | 122000/184988 [39:33<17:53, 58.66it/s, matches=107924, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  66%|██████▌   | 122150/184988 [39:35<18:43, 55.95it/s, matches=108047, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  66%|██████▌   | 122200/184988 [39:36<18:39, 56.11it/s, matches=108091, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  66%|██████▌   | 122250/184988 [39:37<18:44, 55.79it/s, matches=108132, match_rate=88.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  66%|██████▌   | 122300/184988 [39:38<18:02, 57.93it/s, matches=108171, match_rate=88.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  66%|██████▌   | 122400/184988 [39:40<18:53, 55.22it/s, matches=108252, match_rate=88.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  66%|██████▌   | 122550/184988 [39:42<18:11, 57.20it/s, matches=108374, match_rate=88.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)

Error parsing coordinate '52*10'': object of type 'int' has no len()
Error parsing coordinate '52*10'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  67%|██████▋   | 124850/184988 [40:23<17:37, 56.88it/s, matches=110327, match_rate=88.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 124950/184988 [40:25<18:08, 55.16it/s, matches=110409, match_rate=88.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 125000/184988 [40:26<18:08, 55.11it/s, matches=110452, match_rate=88.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 125250/184988 [40:30<17:34, 56.66it/s, matches=110672, match_rate=88.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 125350/184988 [40:32<17:18, 57.43it/s, matches=110753, match_rate=88.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 125400/184988 [40:33<17:28, 56.84it/s, matches=110793, match_rate=88.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 125450/184988 [40:34<17:06, 58.03it/s, matches=110838, match_rate=88.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 125500/184988 [40:35<17:23, 57.01it/s, matches=110880, match_rate=88.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 125550/184988 [40:36<17:51, 55.45it/s, matches=110919, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 125600/184988 [40:36<18:09, 54.50it/s, matches=110958, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 125650/184988 [40:37<18:17, 54.08it/s, matches=111003, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 125700/184988 [40:38<17:56, 55.07it/s, matches=111042, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 125800/184988 [40:40<17:03, 57.85it/s, matches=111124, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 125850/184988 [40:41<17:03, 57.77it/s, matches=111169, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 125900/184988 [40:42<17:13, 57.17it/s, matches=111209, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 125950/184988 [40:43<16:59, 57.91it/s, matches=111250, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 126100/184988 [40:45<16:52, 58.14it/s, matches=111374, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 126150/184988 [40:46<16:54, 58.02it/s, matches=111413, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 126250/184988 [40:48<17:16, 56.67it/s, matches=111494, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 126500/184988 [40:52<16:23, 59.45it/s, matches=111712, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 126550/184988 [40:53<16:38, 58.54it/s, matches=111753, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 126600/184988 [40:54<16:38, 58.46it/s, matches=111794, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 126650/184988 [40:55<16:51, 57.66it/s, matches=111836, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  68%|██████▊   | 126700/184988 [40:56<17:36, 55.17it/s, matches=111879, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  69%|██████▊   | 126800/184988 [40:57<16:53, 57.43it/s, matches=111967, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  69%|██████▊   | 126900/184988 [40:59<16:19, 59.33it/s, matches=112053, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  69%|██████▊   | 126950/184988 [41:00<16:05, 60.09it/s, matches=112095, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  69%|██████▊   | 127050/184988 [41:02<16:34, 58.24it/s, matches=112183, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  69%|██████▊   | 127100/184988 [41:02<16:38, 58.00it/s, matches=112226, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  69%|██████▊   | 127150/184988 [41:03<16:50, 57.23it/s, matches=112273, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  69%|██████▉   | 127200/184988 [41:04<17:16, 55.75it/s, matches=112314, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  69%|██████▉   | 127550/184988 [41:10<16:50, 56.86it/s, matches=112620, match_rate=88.3%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)

Error parsing coordinate '52*23'': object of type 'int' has no len()
Error parsing coordinate '52*23'': object of type 'int' has no len()

Processing accidents:  77%|███████▋  | 142950/184988 [45:42<13:15, 52.86it/s, matches=125718, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  77%|███████▋  | 143000/184988 [45:43<13:03, 53.60it/s, matches=125764, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  77%|███████▋  | 143050/184988 [45:44<12:59, 53.82it/s, matches=125803, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  77%|███████▋  | 143100/184988 [45:45<12:45, 54.69it/s, matches=125842, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  77%|███████▋  | 143250/184988 [45:48<12:27, 55.82it/s, matches=125974, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  77%|███████▋  | 143300/184988 [45:48<12:31, 55.51it/s, matches=126012, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  77%|███████▋  | 143350/184988 [45:49<12:02, 57.65it/s, matches=126045, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 143400/184988 [45:50<12:13, 56.73it/s, matches=126082, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 143450/184988 [45:51<12:16, 56.37it/s, matches=126121, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 143500/184988 [45:52<12:12, 56.64it/s, matches=126163, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 143600/184988 [45:54<11:40, 59.08it/s, matches=126251, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 143650/184988 [45:54<11:51, 58.13it/s, matches=126290, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 143700/184988 [45:55<11:43, 58.66it/s, matches=126334, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 143800/184988 [45:57<11:56, 57.53it/s, matches=126420, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 143850/184988 [45:58<11:46, 58.19it/s, matches=126459, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 143900/184988 [45:59<12:19, 55.58it/s, matches=126501, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 143950/184988 [46:00<12:30, 54.69it/s, matches=126546, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 144000/184988 [46:01<12:20, 55.36it/s, matches=126584, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 144050/184988 [46:02<12:04, 56.52it/s, matches=126620, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 144100/184988 [46:02<11:48, 57.69it/s, matches=126661, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 144150/184988 [46:03<12:11, 55.86it/s, matches=126703, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 144300/184988 [46:06<11:50, 57.30it/s, matches=126831, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 144350/184988 [46:07<11:41, 57.96it/s, matches=126870, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 144400/184988 [46:08<11:44, 57.62it/s, matches=126916, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 144500/184988 [46:09<11:27, 58.92it/s, matches=127001, match_rate=87.9%]

Error parsing coordinate '21*23'': object of type 'int' has no len()
Error parsing coordinate '21*23'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 144550/184988 [46:10<11:36, 58.10it/s, matches=127043, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 144600/184988 [46:11<12:10, 55.32it/s, matches=127087, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 144650/184988 [46:12<11:48, 56.92it/s, matches=127130, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 144700/184988 [46:13<11:32, 58.18it/s, matches=127172, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 144850/184988 [46:15<11:26, 58.44it/s, matches=127299, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 144900/184988 [46:16<11:08, 60.01it/s, matches=127339, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 144950/184988 [46:17<11:13, 59.46it/s, matches=127381, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 145000/184988 [46:18<11:34, 57.57it/s, matches=127424, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  78%|███████▊  | 145200/184988 [46:21<11:10, 59.37it/s, matches=127594, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▊  | 145300/184988 [46:23<10:58, 60.28it/s, matches=127678, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▊  | 145400/184988 [46:25<11:16, 58.51it/s, matches=127763, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▊  | 145550/184988 [46:27<11:21, 57.87it/s, matches=127890, match_rate=87.9%]

Error parsing coordinate '52*28'/81': could not convert string to float: '/81'
Error parsing coordinate '52*28'/81': could not convert string to float: '/81'

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▊  | 145600/184988 [46:28<11:29, 57.10it/s, matches=127934, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)

Error parsing coordinate '21*08'': object of type 'int' has no len()
Error parsing coordinate '21*08'': object of type 'int' has no len()

Processing accidents:  79%|███████▊  | 145650/184988 [46:29<11:25, 57.43it/s, matches=127975, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▉  | 145700/184988 [46:30<11:01, 59.39it/s, matches=128016, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)

Error parsing coordinate '52*21'': object of type 'int' has no len()
Error parsing coordinate '21*00'': object of type 'int' has no len()
Error parsing coordinate '52*21'': object of type 'int' has no len()
Error parsing coordinate '21*00'': object of type 'int' has no len()

Processing accidents:  79%|███████▉  | 145750/184988 [46:31<11:13, 58.26it/s, matches=128055, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▉  | 145800/184988 [46:32<11:08, 58.62it/s, matches=128097, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▉  | 145850/184988 [46:33<11:16, 57.86it/s, matches=128132, match_rate=87.9%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▉  | 145900/184988 [46:33<11:20, 57.48it/s, matches=128165, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▉  | 146000/184988 [46:35<11:37, 55.92it/s, matches=128251, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▉  | 146050/184988 [46:36<11:25, 56.78it/s, matches=128289, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▉  | 146150/184988 [46:38<11:53, 54.40it/s, matches=128374, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▉  | 146250/184988 [46:40<11:19, 57.05it/s, matches=128453, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▉  | 146300/184988 [46:41<11:24, 56.52it/s, matches=128496, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▉  | 146400/184988 [46:42<11:22, 56.55it/s, matches=128581, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▉  | 146450/184988 [46:43<11:17, 56.89it/s, matches=128616, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▉  | 146550/184988 [46:45<11:18, 56.62it/s, matches=128700, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▉  | 146650/184988 [46:47<11:00, 58.04it/s, matches=128788, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▉  | 146750/184988 [46:48<11:05, 57.44it/s, matches=128871, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▉  | 146800/184988 [46:49<11:03, 57.51it/s, matches=128914, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▉  | 146850/184988 [46:50<11:20, 56.04it/s, matches=128957, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▉  | 146900/184988 [46:51<11:11, 56.73it/s, matches=128999, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  79%|███████▉  | 147050/184988 [46:54<10:36, 59.61it/s, matches=129121, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|███████▉  | 147150/184988 [46:55<10:42, 58.90it/s, matches=129195, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|███████▉  | 147200/184988 [46:56<10:47, 58.38it/s, matches=129236, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|███████▉  | 147250/184988 [46:57<11:02, 56.93it/s, matches=129275, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|███████▉  | 147300/184988 [46:58<10:49, 58.04it/s, matches=129318, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|███████▉  | 147350/184988 [46:59<10:39, 58.84it/s, matches=129355, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|███████▉  | 147400/184988 [47:00<10:57, 57.18it/s, matches=129397, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|███████▉  | 147450/184988 [47:00<10:47, 58.00it/s, matches=129436, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)

Error parsing coordinate '21*10'2'4': could not convert string to float: "2'4"
Error parsing coordinate '21*10'2'4': could not convert string to float: "2'4"

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|████████  | 148050/184988 [47:11<10:49, 56.91it/s, matches=129915, match_rate=87.8%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|████████  | 148100/184988 [47:12<10:31, 58.38it/s, matches=129953, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|████████  | 148150/184988 [47:13<10:29, 58.53it/s, matches=129996, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|████████  | 148200/184988 [47:14<10:46, 56.89it/s, matches=130039, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|████████  | 148300/184988 [47:15<10:47, 56.69it/s, matches=130131, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|████████  | 148350/184988 [47:16<10:52, 56.17it/s, matches=130177, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|████████  | 148400/184988 [47:17<11:13, 54.32it/s, matches=130220, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|████████  | 148450/184988 [47:18<11:01, 55.24it/s, matches=130258, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|████████  | 148500/184988 [47:19<10:51, 56.03it/s, matches=130296, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|████████  | 148550/184988 [47:20<10:15, 59.23it/s, matches=130336, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|████████  | 148650/184988 [47:21<10:34, 57.28it/s, matches=130417, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|████████  | 148700/184988 [47:22<10:21, 58.36it/s, matches=130457, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|████████  | 148750/184988 [47:23<11:12, 53.90it/s, matches=130496, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|████████  | 148800/184988 [47:24<11:17, 53.41it/s, matches=130537, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  80%|████████  | 148850/184988 [47:25<11:15, 53.50it/s, matches=130578, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 148950/184988 [47:27<11:00, 54.58it/s, matches=130667, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 149050/184988 [47:29<10:37, 56.39it/s, matches=130749, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 149100/184988 [47:30<10:39, 56.16it/s, matches=130791, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 149150/184988 [47:31<10:37, 56.21it/s, matches=130828, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 149200/184988 [47:31<10:23, 57.44it/s, matches=130870, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 149250/184988 [47:32<10:27, 56.97it/s, matches=130914, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 149300/184988 [47:33<10:32, 56.39it/s, matches=130956, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 149350/184988 [47:34<10:19, 57.57it/s, matches=130998, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 149450/184988 [47:36<10:22, 57.09it/s, matches=131082, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 149550/184988 [47:38<10:25, 56.62it/s, matches=131171, match_rate=87.7%]

Error parsing coordinate '52*11'': object of type 'int' has no len()
Error parsing coordinate '52*11'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 149600/184988 [47:39<10:41, 55.18it/s, matches=131215, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 149650/184988 [47:39<10:12, 57.68it/s, matches=131252, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 149700/184988 [47:40<10:01, 58.70it/s, matches=131295, match_rate=87.7%]

Error parsing coordinate '21*56'': object of type 'int' has no len()
Error parsing coordinate '21*56'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 149750/184988 [47:41<10:08, 57.92it/s, matches=131340, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 149800/184988 [47:42<10:20, 56.73it/s, matches=131380, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 149850/184988 [47:43<10:06, 57.93it/s, matches=131422, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 149900/184988 [47:44<10:00, 58.41it/s, matches=131462, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 149950/184988 [47:44<10:01, 58.24it/s, matches=131507, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 150000/184988 [47:45<10:10, 57.29it/s, matches=131545, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 150100/184988 [47:47<09:54, 58.64it/s, matches=131633, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 150150/184988 [47:48<10:05, 57.50it/s, matches=131676, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 150200/184988 [47:49<10:03, 57.60it/s, matches=131716, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 150250/184988 [47:50<09:58, 58.07it/s, matches=131754, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████  | 150300/184988 [47:50<09:57, 58.02it/s, matches=131796, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████▏ | 150350/184988 [47:51<10:02, 57.50it/s, matches=131836, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████▏ | 150400/184988 [47:52<09:59, 57.67it/s, matches=131877, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████▏ | 150550/184988 [47:55<10:26, 54.93it/s, matches=131994, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████▏ | 150600/184988 [47:56<10:29, 54.65it/s, matches=132030, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████▏ | 150650/184988 [47:57<10:19, 55.47it/s, matches=132070, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████▏ | 150700/184988 [47:58<10:03, 56.80it/s, matches=132110, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  81%|████████▏ | 150750/184988 [47:58<09:54, 57.60it/s, matches=132153, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 150800/184988 [47:59<09:37, 59.23it/s, matches=132194, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 150850/184988 [48:00<09:52, 57.61it/s, matches=132228, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 150900/184988 [48:01<10:04, 56.41it/s, matches=132271, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 150950/184988 [48:02<09:43, 58.29it/s, matches=132310, match_rate=87.7%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 151050/184988 [48:04<09:42, 58.31it/s, matches=132393, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 151150/184988 [48:05<09:37, 58.61it/s, matches=132476, match_rate=87.6%]

Error parsing coordinate '21*08'': object of type 'int' has no len()
Error parsing coordinate '21*08'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 151250/184988 [48:07<09:26, 59.56it/s, matches=132557, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 151300/184988 [48:08<09:35, 58.58it/s, matches=132600, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 151400/184988 [48:09<09:31, 58.81it/s, matches=132686, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 151450/184988 [48:10<09:14, 60.48it/s, matches=132730, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 151600/184988 [48:13<09:13, 60.32it/s, matches=132855, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 151650/184988 [48:14<09:24, 59.10it/s, matches=132897, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 151700/184988 [48:14<09:09, 60.57it/s, matches=132936, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 151750/184988 [48:15<09:16, 59.75it/s, matches=132981, match_rate=87.6%]

Error parsing coordinate '21*97'': object of type 'int' has no len()
Error parsing coordinate '21*97'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 151850/184988 [48:17<09:23, 58.84it/s, matches=133063, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 151900/184988 [48:18<09:12, 59.93it/s, matches=133100, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 151950/184988 [48:19<08:57, 61.47it/s, matches=133141, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 152000/184988 [48:19<09:06, 60.34it/s, matches=133183, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 152050/184988 [48:20<08:47, 62.42it/s, matches=133218, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 152200/184988 [48:23<09:18, 58.70it/s, matches=133345, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 152300/184988 [48:25<09:29, 57.39it/s, matches=133432, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 152350/184988 [48:25<09:22, 58.05it/s, matches=133473, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 152400/184988 [48:26<09:04, 59.85it/s, matches=133521, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 152450/184988 [48:27<08:58, 60.43it/s, matches=133564, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 152500/184988 [48:28<09:08, 59.28it/s, matches=133607, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  82%|████████▏ | 152600/184988 [48:30<09:09, 58.94it/s, matches=133683, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  83%|████████▎ | 152650/184988 [48:30<08:58, 60.07it/s, matches=133723, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  83%|████████▎ | 152700/184988 [48:31<09:07, 58.93it/s, matches=133762, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  83%|████████▎ | 152750/184988 [48:32<09:55, 54.09it/s, matches=133801, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  83%|████████▎ | 152850/184988 [48:34<09:38, 55.52it/s, matches=133882, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  83%|████████▎ | 152900/184988 [48:35<09:44, 54.90it/s, matches=133920, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  83%|████████▎ | 152950/184988 [48:36<09:30, 56.15it/s, matches=133961, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  83%|████████▎ | 153000/184988 [48:37<09:21, 56.98it/s, matches=134004, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  83%|████████▎ | 153050/184988 [48:38<09:07, 58.29it/s, matches=134041, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  83%|████████▎ | 153100/184988 [48:38<09:06, 58.35it/s, matches=134080, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  83%|████████▎ | 153150/184988 [48:39<09:12, 57.65it/s, matches=134117, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  83%|████████▎ | 153200/184988 [48:40<09:13, 57.38it/s, matches=134158, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  83%|████████▎ | 153250/184988 [48:41<09:11, 57.57it/s, matches=134197, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  83%|████████▎ | 153350/184988 [48:43<09:11, 57.40it/s, matches=134275, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  83%|████████▎ | 153400/184988 [48:44<09:06, 57.79it/s, matches=134315, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  83%|████████▎ | 153500/184988 [48:45<08:40, 60.52it/s, matches=134399, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  83%|████████▎ | 153550/184988 [48:46<08:33, 61.25it/s, matches=134437, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  83%|████████▎ | 153600/184988 [48:47<08:42, 60.11it/s, matches=134481, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  83%|████████▎ | 153700/184988 [48:49<08:58, 58.06it/s, matches=134569, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  83%|████████▎ | 153750/184988 [48:50<09:16, 56.17it/s, matches=134610, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  83%|████████▎ | 153800/184988 [48:51<09:14, 56.21it/s, matches=134650, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  83%|████████▎ | 153850/184988 [48:51<09:01, 57.55it/s, matches=134696, match_rate=87.6%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)

Error parsing coordinate '21*19'': object of type 'int' has no len()
Error parsing coordinate '21*19'': object of type 'int' has no len()

Processing accidents:  83%|████████▎ | 154350/184988 [49:00<09:01, 56.59it/s, matches=135121, match_rate=87.5%]

Error parsing coordinate '21*52'': object of type 'int' has no len()
Error parsing coordinate '21*52'': object of type 'int' has no len()

Processing accidents:  83%|████████▎ | 154450/184988 [49:02<08:38, 58.93it/s, matches=135208, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▎ | 154500/184988 [49:03<08:55, 56.91it/s, matches=135248, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▎ | 154550/184988 [49:03<08:53, 57.09it/s, matches=135292, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▎ | 154600/184988 [49:04<08:58, 56.44it/s, matches=135332, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▎ | 154650/184988 [49:05<08:51, 57.12it/s, matches=135369, match_rate=87.5%]

Error parsing coordinate '21*12'': object of type 'int' has no len()
Error parsing coordinate '21*12'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▎ | 154700/184988 [49:06<09:23, 53.72it/s, matches=135411, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▎ | 154750/184988 [49:07<09:02, 55.72it/s, matches=135452, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▎ | 154800/184988 [49:08<09:01, 55.70it/s, matches=135492, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▎ | 154850/184988 [49:09<08:51, 56.72it/s, matches=135530, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▎ | 154900/184988 [49:10<08:31, 58.77it/s, matches=135573, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 154950/184988 [49:10<08:28, 59.08it/s, matches=135616, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 155000/184988 [49:11<08:31, 58.67it/s, matches=135657, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 155050/184988 [49:12<08:28, 58.84it/s, matches=135696, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)

Error parsing coordinate '21*05'': object of type 'int' has no len()
Error parsing coordinate '21*05'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 155100/184988 [49:13<08:45, 56.85it/s, matches=135735, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 155150/184988 [49:14<08:55, 55.71it/s, matches=135774, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 155200/184988 [49:15<09:04, 54.69it/s, matches=135817, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 155250/184988 [49:16<08:56, 55.41it/s, matches=135859, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 155300/184988 [49:17<09:07, 54.20it/s, matches=135900, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 155350/184988 [49:18<09:02, 54.58it/s, matches=135943, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 155400/184988 [49:19<08:46, 56.19it/s, matches=135981, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 155450/184988 [49:19<08:42, 56.48it/s, matches=136021, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 155550/184988 [49:21<08:44, 56.16it/s, matches=136107, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 155600/184988 [49:22<08:35, 56.97it/s, matches=136151, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 155650/184988 [49:23<08:32, 57.21it/s, matches=136191, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)

Error parsing coordinate '52*10'': object of type 'int' has no len()
Error parsing coordinate '20*59'': object of type 'int' has no len()
Error parsing coordinate '52*10'': object of type 'int' has no len()
Error parsing coordinate '20*59'': object of type 'int' has no len()

Processing accidents:  84%|████████▍ | 155750/184988 [49:25<08:43, 55.82it/s, matches=136278, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 155800/184988 [49:26<08:38, 56.33it/s, matches=136321, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 155850/184988 [49:26<08:22, 58.04it/s, matches=136357, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 155900/184988 [49:27<08:16, 58.59it/s, matches=136393, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 155950/184988 [49:28<08:18, 58.25it/s, matches=136430, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 156000/184988 [49:29<08:21, 57.76it/s, matches=136472, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 156050/184988 [49:30<08:20, 57.85it/s, matches=136511, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 156100/184988 [49:31<08:18, 57.95it/s, matches=136549, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 156150/184988 [49:32<08:19, 57.71it/s, matches=136591, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 156200/184988 [49:33<08:36, 55.70it/s, matches=136634, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 156250/184988 [49:34<08:42, 54.99it/s, matches=136677, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  84%|████████▍ | 156300/184988 [49:34<08:18, 57.55it/s, matches=136716, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▍ | 156350/184988 [49:35<08:22, 56.95it/s, matches=136757, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▍ | 156450/184988 [49:37<08:22, 56.80it/s, matches=136840, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▍ | 156500/184988 [49:38<08:19, 57.01it/s, matches=136876, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▍ | 156550/184988 [49:39<08:12, 57.69it/s, matches=136919, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▍ | 156600/184988 [49:40<08:17, 57.07it/s, matches=136959, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▍ | 156650/184988 [49:41<08:40, 54.48it/s, matches=136999, match_rate=87.5%]

Error parsing coordinate '21*36'': object of type 'int' has no len()
Error parsing coordinate '21*36'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▍ | 156750/184988 [49:42<08:32, 55.10it/s, matches=137078, match_rate=87.5%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▍ | 156850/184988 [49:44<08:38, 54.24it/s, matches=137164, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▍ | 156900/184988 [49:45<08:36, 54.39it/s, matches=137202, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▍ | 156950/184988 [49:46<08:15, 56.56it/s, matches=137245, match_rate=87.4%]

Error parsing coordinate '21*29'': object of type 'int' has no len()
Error parsing coordinate '21*29'': object of type 'int' has no len()

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▍ | 157000/184988 [49:47<08:00, 58.24it/s, matches=137287, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▍ | 157050/184988 [49:48<07:53, 58.99it/s, matches=137325, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▍ | 157100/184988 [49:48<07:39, 60.68it/s, matches=137365, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▍ | 157150/184988 [49:49<07:53, 58.77it/s, matches=137403, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▍ | 157200/184988 [49:50<07:51, 58.90it/s, matches=137443, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▌ | 157250/184988 [49:51<08:03, 57.40it/s, matches=137480, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▌ | 157300/184988 [49:52<08:14, 56.02it/s, matches=137523, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▌ | 157350/184988 [49:53<08:09, 56.50it/s, matches=137560, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▌ | 157400/184988 [49:54<07:50, 58.64it/s, matches=137604, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▌ | 157500/184988 [49:55<07:39, 59.81it/s, matches=137688, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▌ | 157550/184988 [49:56<07:52, 58.03it/s, matches=137731, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▌ | 157600/184988 [49:57<08:01, 56.86it/s, matches=137774, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▌ | 157650/184988 [49:58<07:56, 57.40it/s, matches=137816, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▌ | 157700/184988 [49:59<08:04, 56.38it/s, matches=137855, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▌ | 157750/184988 [50:00<08:10, 55.55it/s, matches=137898, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▌ | 157800/184988 [50:01<07:56, 57.10it/s, matches=137942, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▌ | 157850/184988 [50:02<08:08, 55.60it/s, matches=137983, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▌ | 157900/184988 [50:02<07:52, 57.28it/s, matches=138030, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▌ | 158000/184988 [50:04<08:07, 55.34it/s, matches=138113, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▌ | 158100/184988 [50:06<08:02, 55.74it/s, matches=138202, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  85%|████████▌ | 158150/184988 [50:07<07:51, 56.92it/s, matches=138244, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  86%|████████▌ | 158200/184988 [50:08<07:42, 57.86it/s, matches=138282, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  86%|████████▌ | 158250/184988 [50:09<07:38, 58.33it/s, matches=138327, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  86%|████████▌ | 158300/184988 [50:09<07:31, 59.16it/s, matches=138368, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  86%|████████▌ | 158350/184988 [50:10<07:27, 59.50it/s, matches=138410, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  86%|████████▌ | 158400/184988 [50:11<07:30, 58.98it/s, matches=138456, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  86%|████████▌ | 158450/184988 [50:12<07:32, 58.67it/s, matches=138497, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)

Error parsing coordinate '30*5+'285': could not convert string to float: '5+'
Error parsing coordinate '30*5+'285': could not convert string to float: '5+'

Processing accidents:  86%|████████▌ | 159550/184988 [50:31<07:06, 59.58it/s, matches=139401, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  86%|████████▋ | 159600/184988 [50:31<07:07, 59.32it/s, matches=139445, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents:  86%|████████▋ | 159650/184988 [50:32<07:03, 59.81it/s, matches=139486, match_rate=87.4%]C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\shapely\measurement.py:81: RuntimeWarning: invalid value encountered in distance
  return lib.distance(a, b, **kwargs)
Processing accidents: 100%|█████████▉| 184953/184988 [58:01<00:00, 53.12it/s, matches=161371, match_rate=87.2%]

==================================================
FINAL RESULTS:
Total matches created: 184127
Similarity score distribution:
count    182364.000000
mean         94.382578
std          10.356461
min          60.000000
25%          91.666667
50%         100.000000
75%         100.000000
max         100.000000
Name: similarity_score, dtype: float64

Distance to street distribution (meters):
count    182364.000
mean            inf
std             NaN
min           0.000
25%           4.800
50%          20.000
75%         116.225
max             inf
Name: distance_to_street_meters, dtype: float64
High quality matches (>= 80% similarity): 157716
Medium quality matches (70-79% similarity): 26411

10 closest matches:
      accident_id      accident_street       matched_street  similarity_score  \
2560    106708293            ŚWIDERSKA            ŚWIDERSKA             100.0
2692    106712394             SYCOWSKA             SYCOWSKA             100.0
3040    106722000               STAWKI               STAWKI             100.0
3230    106723546             TORUŃSKA             TORUŃSKA             100.0
4462    106761986            PŁOWIECKA            PŁOWIECKA             100.0
4521    106763811           WROCŁAWSKA           WROCŁAWSKA             100.0
4699    106766702        SKIERNIEWICKA        SKIERNIEWICKA             100.0
4914    106780737         PRZYCZÓŁKOWA         PRZYCZÓŁKOWA             100.0
6579    106807230  ALEJE JEROZOLIMSKIE  ALEJE JEROZOLIMSKIE             100.0
6924    106816291         OSTROBRAMSKA         OSTROBRAMSKA             100.0

      distance_to_street_meters
2560                        0.0
2692                        0.0
3040                        0.0
3230                        0.0
4462                        0.0
4521                        0.0
4699                        0.0
4914                        0.0
6579                        0.0
6924                        0.0

C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

# Final processing

In [64]:
final_df = pd.DataFrame(matches)

final_df.to_csv("gis/street_matches_v4.tsv", sep="\t")

In [65]:
updated_latlon = final_df[["accident_id", "best_lat", "best_lon"]].rename({"accident_id": "ID", "best_lat": "lat", "best_lon": "lon"}, axis=1).dropna().set_index("ID")
updated_latlon = updated_latlon[~updated_latlon.index.duplicated()]
accidents_df = accidents_df.set_index("ID") if accidents_df.index.name.lower() != "id" else accidents_df
accidents_df.update(updated_latlon)

In [66]:
accidents_df.reset_index().drop("geometry", axis=1).to_csv("csv/sewik_accidents_v4.csv", index=False)

In [67]:
accidents_df = gpd.GeoDataFrame(
    accidents_df, 
    geometry=gpd.GeoSeries.from_xy(
        accidents_df["lon"], accidents_df["lat"], crs="WGS84"))

accidents_df.reset_index().loc[
    accidents_df.reset_index().geometry.is_valid,
        [
            'ID', 'year', 'WOJ', 'WSP_GPS_X', 'WSP_GPS_Y', 'MIEJSCOWOSC' ,
            'ULICA_ADRES', 'NUMER_DOMU', "geometry"]
        ].to_file('gis/sewik_accidents_points_v4.shp', driver='ESRI Shapefile')

C:\Users\Witold\AppData\Local\Temp\ipykernel_10756\3333873842.py:11: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  ].to_file('gis/sewik_accidents_points_v4.shp', driver='ESRI Shapefile')
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'MIEJSCOWOSC' to 'MIEJSCOWOS'
  ogr_write(
C:\Users\Witold\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\pyogrio\raw.py:723: RuntimeWarning: Normalized/laundered field name: 'ULICA_ADRES' to 'ULICA_ADRE'
  ogr_write(